---
permalink: protect-scsql/concept_when_to_schedule_verification_jobs.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: 'Embora o SnapCenter possa verificar os backups imediatamente após a criação, isso pode aumentar significativamente o tempo necessário para concluir a tarefa de backup e usar muitos recursos. Portanto, é quase sempre melhor agendar a verificação em um trabalho separado para um momento posterior. Por exemplo, se você fizer backup de um banco de dados às 5:00 horas por dia, poderá agendar a verificação para ocorrer uma hora depois às 6:00 horas' 
---
= Quando agendar trabalhos de verificação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Embora o SnapCenter possa verificar os backups imediatamente após a criação, isso pode aumentar significativamente o tempo necessário para concluir a tarefa de backup e usar muitos recursos. Portanto, é quase sempre melhor agendar a verificação em um trabalho separado para um momento posterior. Por exemplo, se você fizer backup de um banco de dados às 5:00 horas por dia, poderá agendar a verificação para ocorrer uma hora depois às 6:00 horas

Pelo mesmo motivo, geralmente não é necessário executar a verificação de backup toda vez que você executar um backup. Realizar a verificação em intervalos regulares, mas menos frequentes, geralmente é suficiente para garantir a integridade do backup. Um único trabalho de verificação pode verificar vários backups ao mesmo tempo.
