---
permalink: protect-scsql/task_reseed_availability_group_databases.html 
sidebar: sidebar 
keywords: reseed 
summary: Reseed é uma opção para restaurar bancos de dados de grupos de disponibilidade. Se um banco de dados secundário ficar fora de sincronização com o banco de dados primário em um AG, você poderá fazer a semente novamente do banco de dados secundário. 
---
= Reseed Availability Group Databases
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reseed é uma opção para restaurar bancos de dados do Availability Group (AG). Se um banco de dados secundário ficar fora de sincronização com o banco de dados primário em um AG, você poderá fazer a semente novamente do banco de dados secundário.

.Antes de começar
* Você deve ter criado o backup do banco de dados AG secundário que você deseja restaurar.
* O servidor SnapCenter e o host do plug-in devem ter a mesma versão do SnapCenter instalada.


.Sobre esta tarefa
* Não é possível executar a operação de semente em bancos de dados primários.
* Não é possível executar uma operação de semente novamente se o banco de dados de réplica for removido do grupo de disponibilidade. Quando a réplica é removida, a operação de resemente falha.
* Ao executar a operação de repleed no banco de dados SQL Availability Group, você não deve acionar backups de log nos bancos de dados de réplica desse banco de dados de grupo de disponibilidade. Se você acionar backups de log durante a operação de repleed, a operação de repleed falha com o banco de dados espelhado, "database_name" tem dados de log de transação insuficientes para preservar a cadeia de backup de log da mensagem de erro principal do banco de dados.


.Passos
. No painel de navegação à esquerda, clique em *Resources* e selecione *SnapCenter Plug-in para SQL Server* na lista.
. Na página recursos, selecione *Banco de dados* na lista *Exibir*.
. Selecione a base de dados AG secundária na lista.
. Clique em *Reseed*.
. Monitorize o progresso da operação clicando em *Monitor* > *trabalhos*.

