---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: Com o SnapCenter, você pode criar clones de um grupo de recursos ou banco de dados. Você pode executar um clone sob demanda ou agendar operações de clone recorrentes de um grupo de recursos ou banco de dados . Se você clonar um backup periodicamente, poderá usar o clone para desenvolver aplicativos, preencher dados ou recuperar dados. 
---
= Execute o ciclo de vida do clone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Com o SnapCenter, você pode criar clones de um grupo de recursos ou banco de dados. Você pode executar um clone sob demanda ou agendar operações de clone recorrentes de um grupo de recursos ou banco de dados. Se você clonar um backup periodicamente, poderá usar o clone para desenvolver aplicativos, preencher dados ou recuperar dados.

O SnapCenter permite que você programe várias operações de clone para serem executadas simultaneamente em vários servidores.

.Antes de começar
* Durante a clonagem para uma instância de banco de dados autônoma, verifique se o caminho do ponto de montagem existe e se ele é um disco dedicado.
* Durante a clonagem para uma instância de cluster de failover (FCI), certifique-se de que os pontos de montagem existem, é um disco compartilhado e o caminho e o FCI devem pertencer ao mesmo grupo de recursos SQL.
* Se o banco de dados de origem ou a instância de destino estiver em um volume compartilhado de cluster (csv), o banco de dados clonado estará no csv.



NOTE: Para ambientes virtuais (VMDK/RDM), verifique se o ponto de montagem é um disco dedicado.

.Sobre esta tarefa
* O SCRIPT_PATH é definido usando a chave PredefinedWindowsScriptsDirectory localizada no arquivo SMCoreServiceHost.exe.Config do host do plug-in.
+
Se necessário, você pode alterar esse caminho e reiniciar o serviço SMcore. É recomendável usar o caminho padrão para segurança.

+
O valor da chave pode ser exibido do swagger através da API: API /4,7/configsettings

+
Você pode usar a API GET para exibir o valor da chave. A API SET não é suportada.

* A maioria dos campos nas páginas do assistente Clone Lifecycle são auto-explicativos. As informações a seguir descrevem os campos para os quais você pode precisar de orientação.
* Para a versão ONTAP 9.12,1 e inferior, se você especificar um período de bloqueio do Snapshot, os clones criados a partir dos snapshots à prova de violação herdarão o tempo de expiração do SnapLock. O administrador do storage deve limpar manualmente os clones após o tempo de expiração do SnapLock.


.Passos
. No painel de navegação esquerdo, clique em *Resources* e selecione o plug-in apropriado na lista.
. Na página recursos, selecione *Banco de dados* ou *Grupo de recursos* na lista *Exibir*.
. Selecione o grupo de recursos ou banco de dados e clique em *Clone Lifecycle*.
. Na página Opções, execute as seguintes ações:
+
|===
| Para este campo... | Faça isso... 


 a| 
Clone o nome da tarefa
 a| 
Especifique o nome da tarefa do ciclo de vida do clone que ajuda a monitorar e modificar a tarefa do ciclo de vida do clone.



 a| 
Servidor clone
 a| 
Escolha o host no qual o clone deve ser colocado.



 a| 
Instância de clone
 a| 
Escolha a instância clone para a qual você deseja clonar o banco de dados. Essa instância SQL deve estar localizada no servidor clone especificado.



 a| 
Sufixo clone
 a| 
Digite um sufixo que será anexado ao banco de dados clone para identificar que é um clone. Cada instância SQL usada para criar um grupo de recursos clone deve ter um nome de banco de dados exclusivo. Por exemplo, se o grupo de recursos clone contiver um banco de dados de origem "d.B1" de uma instância SQL "'inst1" e se "d.B1"" for clonado para "'inst1", então o nome do banco de dados clone deve ser "d.B1__clone". "'__clone" é um sufixo obrigatório definido pelo usuário porque o banco de dados é clonado para a mesma instância. Se "d.B1" for clonado para a instância SQL "'inst2", então o nome do banco de dados clone pode permanecer "d.B1" (o sufixo é opcional) porque o banco de dados é clonado para uma instância diferente.



 a| 
Atribuir automaticamente o ponto de montagem ou atribuir automaticamente o ponto de montagem do volume sob o caminho
 a| 
Escolha se deseja atribuir automaticamente um ponto de montagem ou um ponto de montagem de volume sob um caminho. Escolher atribuir automaticamente um ponto de montagem de volume sob um caminho permite fornecer um diretório específico. Os pontos de montagem serão criados dentro desse diretório. Antes de escolher essa opção, você deve garantir que o diretório esteja vazio. Se houver um banco de dados no diretório, o banco de dados estará em um estado inválido após a operação de montagem.

|===
. Na página local, selecione um local de armazenamento para criar um clone.
. Na página Script, insira o caminho e os argumentos do prescritor ou postscript que devem ser executados antes ou depois da operação clone, respetivamente.
+
Por exemplo, você pode executar um script para atualizar traps SNMP, automatizar alertas, enviar logs e assim por diante.

+

NOTE: O caminho de prescripts ou postscripts não deve incluir unidades ou compartilhamentos. O caminho deve ser relativo ao SCRIPT_path.

+
O tempo limite padrão do script é de 60 segundos.

. Na página Agendar, execute uma das seguintes ações:
+
** Selecione *Executar agora* se quiser executar a tarefa clone imediatamente.
** Selecione *Configurar agendamento* quando quiser determinar com que frequência a operação de clone deve ocorrer, quando a programação de clones deve ser iniciada, em que dia a operação de clone deve ocorrer, quando a programação deve expirar e se os clones devem ser excluídos após a expiração da programação.


. Na página notificação, na lista suspensa *preferência de e-mail*, selecione os cenários nos quais você deseja enviar os e-mails.
+
Você também deve especificar os endereços de e-mail do remetente e do destinatário e o assunto do e-mail. Se quiser anexar o relatório da operação clone executada, selecione *Anexar Relatório de trabalho*.

+

NOTE: Para notificação por e-mail, você deve ter especificado os detalhes do servidor SMTP usando a GUI ou o comando PowerShell SET-SmtpServer.

+
Para EMS, pode consultar https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["Gerir a recolha de dados EMS"]

. Revise o resumo e clique em *Finish*.


Deve monitorizar o processo de clonagem utilizando a página *Monitor* > *trabalhos*.
