---
permalink: protect-scsql/task_configure_credentials_for_an_individual_sql_server_resource.html 
sidebar: sidebar 
keywords: credentials 
summary: Você pode configurar credenciais para executar tarefas de proteção de dados em recursos individuais do SQL Server para cada usuário. 
---
= Configurar credenciais para um recurso do SQL Server individual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar credenciais para executar tarefas de proteção de dados em recursos individuais do SQL Server para cada usuário. Embora você possa configurar as credenciais globalmente, talvez você queira fazer isso apenas para um recurso específico.

.Sobre esta tarefa
* Se você estiver usando credenciais do Windows para autenticação, você deve configurar sua credencial antes de instalar plug-ins.
+
No entanto, se você estiver usando uma instância do SQL Server para autenticação, você deve adicionar a credencial após a instalação de plug-ins.

* Se você ativou a autenticação SQL durante a configuração das credenciais, a instância descoberta ou o banco de dados será exibida com um ícone de cadeado de cor vermelha.
+
Se o ícone de cadeado aparecer, você deve especificar as credenciais da instância ou do banco de dados para adicionar com êxito a instância ou o banco de dados a um grupo de recursos.

* Você deve atribuir a credencial a um usuário de controle de acesso baseado em função (RBAC) sem acesso sysadmin quando as seguintes condições forem atendidas:
+
** A credencial é atribuída a uma instância SQL.
** A instância ou host SQL é atribuída a um usuário RBAC.
+
O usuário deve ter o grupo de recursos e o Privileges de backup.







== Etapa 1: Adicionar e configurar credenciais

. No painel de navegação esquerdo, selecione *Configurações*.
. Na página Configurações, selecione *Credential*.
+
.. Para adicionar uma nova credencial, selecione *novo*.
.. Na página Credential (credencial), configure as credenciais:
+
[cols="1,3"]
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Introduza um nome para as credenciais.



 a| 
Nome de utilizador
 a| 
Introduza o nome de utilizador utilizado para a autenticação do SQL Server.

*** O administrador de domínio ou qualquer membro do grupo de administradores especificam o administrador do domínio ou qualquer membro do grupo de administradores no sistema no qual você está instalando o plug-in do SnapCenter. Os formatos válidos para o campo *Nome de usuário* são:
+
**** _NetBIOS_username_
**** _Domain FQDN_username_


*** Administrador local (somente para grupos de trabalho) para sistemas que pertencem a um grupo de trabalho, especifique o administrador local interno no sistema no qual você está instalando o plug-in SnapCenter. Você pode especificar uma conta de usuário local que pertence ao grupo de administradores locais se a conta de usuário tiver Privileges elevado ou o recurso de controle de acesso do usuário estiver desativado no sistema host. O formato válido para o campo *Username* é: _Username_




 a| 
Palavra-passe
 a| 
Introduza a palavra-passe utilizada para autenticação.



 a| 
Modo de autenticação
 a| 
Selecione o modo de autenticação do SQL Server. Você também pode escolher a autenticação do Windows se o usuário do Windows tiver sysadmin Privileges no servidor SQL.



 a| 
Host
 a| 
Selecione o host.



 a| 
Instância do SQL Server
 a| 
Selecione a instância do SQL Server.

|===
.. Selecione *OK* para adicionar a credencial.






== Etapa 2: Configurar instâncias

. No painel de navegação esquerdo, selecione *Resources*.
. Na página recursos, selecione *Instância* na lista *Exibir*.
+
.. Selecione imagem::../media/filter_icon.png[filter icon] e, em seguida, selecione o nome do host para filtrar as instâncias.
.. Selecione imagem::../media/filter_icon.png[filter icon] para fechar o painel de filtro.


. Na página proteção de instância, proteja a instância e, se necessário, selecione *Configurar credenciais*.
+
Se o usuário que está conetado ao servidor SnapCenter não tiver acesso ao plug-in do SnapCenter para Microsoft SQL Server, o usuário terá que configurar as credenciais.

+

NOTE: A opção credencial não se aplica a bancos de dados e grupos de disponibilidade.

. Selecione *Atualizar recursos*.

