---
permalink: protect-scsql/task_install_snapcenter_plug_in_package_for_windows_server_on_multiple_remote_hosts_using_cmdlets_scsql.html 
sidebar: sidebar 
keywords: credentials 
summary: Você pode instalar o plug-in do SnapCenter para Microsoft SQL Server em vários hosts simultaneamente usando o cmdlet Install-SmHostPackage PowerShell. 
---
= Instale o plug-in do SnapCenter para Microsoft SQL Server em vários hosts remotos usando cmdlets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instalar o plug-in do SnapCenter para Microsoft SQL Server em vários hosts simultaneamente usando o cmdlet Install-SmHostPackage PowerShell.

.Antes de começar
Você deve ter feito login no SnapCenter como um usuário de domínio com direitos de administrador local em cada host no qual deseja instalar o pacote de plug-in.

.Passos
. Inicie o PowerShell.
. No host do servidor SnapCenter, estabeleça uma sessão usando o cmdlet Open-SmConnection e insira suas credenciais.
. Instale o plug-in do SnapCenter para Microsoft SQL Server em vários hosts remotos usando o cmdlet Install-SmHostPackage e os parâmetros necessários.
+
As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _get-Help command_name_. Em alternativa, pode também consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência de cmdlet do software SnapCenter"^].

+
Você pode usar a opção -skipprecheck quando já tiver instalado os plug-ins manualmente e não quiser validar se o host atende aos requisitos para instalar o plug-in.

. Insira suas credenciais para instalação remota.

