---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter. Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados em bancos de dados ou sistemas de arquivos do Windows. 
---
= Configure credenciais para o pacote de plug-ins do SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter. Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados em bancos de dados ou sistemas de arquivos do Windows.

.Antes de começar
* Você deve configurar as credenciais do Windows antes de instalar os plug-ins.
* Você deve configurar as credenciais com o Privileges de administrador, incluindo direitos de administrador no host remoto.
* Autenticação SQL em hosts Windows
+
Você deve configurar credenciais SQL depois de instalar plug-ins.

+
Se você estiver implantando o plug-in do SnapCenter para o Microsoft SQL Server, deverá configurar credenciais SQL após a instalação dos plug-ins. Configure uma credencial para um usuário com permissões sysadmin do SQL Server.

+
O método de autenticação SQL é autenticado em uma instância do SQL Server. Isso significa que uma instância do SQL Server deve ser descoberta no SnapCenter. Portanto, antes de adicionar uma credencial SQL, você deve adicionar um host, instalar pacotes de plug-in e atualizar recursos. Você precisa de autenticação do SQL Server para executar operações como agendamento ou descoberta de recursos.



.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credential*.
. Clique em *novo*.
. Na página Credential (credencial), especifique as informações necessárias para configurar credenciais:
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Introduza um nome para a credencial.



 a| 
Nome de utilizador/Palavra-passe
 a| 
Introduza o nome de utilizador e a palavra-passe a utilizar para a autenticação.

** Administrador de domínio
+
Especifique o administrador de domínio no sistema no qual você está instalando o plug-in SnapCenter. Os formatos válidos para o campo Nome de usuário são:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrador local (apenas para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local incorporado no sistema no qual você está instalando o plug-in SnapCenter. Você pode especificar uma conta de usuário local que pertence ao grupo de administradores locais se a conta de usuário tiver Privileges elevado ou o recurso de controle de acesso do usuário estiver desativado no sistema host. O formato válido para o campo Nome de usuário é: `UserName`

+
Não use aspas duplas (") ou backtick (') nas senhas. Você não deve usar os símbolos menos de (>) e exclamação (!) juntos em senhas. Por exemplo, lessthan!10, lessthan10You!, backtick'12.





 a| 
Modo de autenticação
 a| 
Selecione o modo de autenticação que pretende utilizar. Se você selecionar o modo de autenticação SQL, você também deve especificar a instância do servidor SQL e o host onde a instância SQL está localizada.

|===
. Clique em *OK*.


Depois de concluir a configuração das credenciais, talvez você queira atribuir a manutenção de credenciais a um usuário ou grupo de usuários na página Usuário e Acesso.
