---
permalink: protect-sco/concept_snapcenter_plug_in_for_oracle_database_features.html 
sidebar: sidebar 
keywords: plug-in for Oracle features 
summary: O plug-in para banco de dados Oracle se integra ao banco de dados Oracle no host Linux ou AIX e com tecnologias NetApp no sistema de armazenamento. 
---
= Recursos do Plug-in para banco de dados Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O plug-in para banco de dados Oracle se integra ao banco de dados Oracle no host Linux ou AIX e com tecnologias NetApp no sistema de armazenamento.

* Interface gráfica do usuário unificada
+
A interface do SnapCenter fornece padronização e consistência em plug-ins e ambientes. A interface do SnapCenter permite concluir operações consistentes de backup, restauração, recuperação e clone em plug-ins, usar relatórios centralizados, usar visualizações de dashboard rápidas, configurar controle de acesso baseado em funções (RBAC) e monitorar tarefas em todos os plug-ins.

* Administração central automatizada
+
Você pode agendar operações de backup e clone, configurar a retenção de backup baseada em política e executar operações de restauração. Você também pode monitorar proativamente seu ambiente configurando o SnapCenter para enviar alertas por e-mail.

* Tecnologia NetApp Snapshot sem interrupções
+
O SnapCenter usa a tecnologia NetApp Snapshot com o plug-in para banco de dados Oracle e plug-in para UNIX para fazer backup de bancos de dados. Os snapshots consomem espaço mínimo de storage.



O Plug-in para Oracle Database também oferece os seguintes benefícios:

* Suporte para fluxos de trabalho de backup, restauração, clonagem, montagem, desmontagem e verificação
* Descoberta automática de bancos de dados Oracle configurados no host
* Suporte para catalogação e descatalogação usando o Oracle Recovery Manager (RMAN)
* Delegação de funções centralizada e segurança compatível com RBAC
+
Você também pode definir as credenciais para que os usuários autorizados do SnapCenter tenham permissões no nível do aplicativo.

* Suporte para gerenciamento de logs de arquivamento (ALM) para operações de restauração e clonagem
* Criação de cópias pontuais e com uso eficiente de espaço de bancos de dados de produção para teste ou extração de dados usando a tecnologia NetApp FlexClone
+
É necessária uma licença FlexClone no sistema de storage onde você deseja criar o clone.

* Suporte ao recurso de grupo de consistência (CG) do ONTAP como parte da criação de backups em ambientes SAN e ASM
* Verificação de backup sem interrupções e automatizada
* Funcionalidade de executar vários backups simultaneamente em vários hosts de banco de dados
+
Em uma única operação, os snapshots são consolidados quando os bancos de dados em um único host compartilham o mesmo volume.

* Suporte para infraestruturas físicas e virtualizadas
* Suporte para NFS, iSCSI, Fibre Channel (FC), RDM, VMDK em NFS e VMFS, e ASM em NFS, SAN, RDM e VMDK
* Suporte para o recurso de mapa LUN seletivo (SLM) do ONTAP
+
Habilitado por padrão, o recurso SLM deteta periodicamente os LUNs que não têm caminhos otimizados e os corrige. Você pode configurar o SLM modificando os parâmetros no arquivo scu.properties localizado em /var/opt/SnapCenter/scu/etc.

+
** Você pode desativar isso definindo o valor do parâmetro ENABLE_LUNPATH_MONITORING como false.
** Você pode especificar a frequência em que os caminhos LUN serão corrigidos automaticamente atribuindo o valor (em horas) ao parâmetro LUNPATH_MONITORING_INTERVAL. Para obter informações sobre o SLM, consulte https://docs.netapp.com/us-en/ontap/san-admin/index.html["Seção Administração de SAN ONTAP 9"^].


* Suporte para memória não volátil Express (NVMe) no Linux
+
** O NVMe útil deve ser instalado no host.
+
É necessário instalar o NVMe util para clonar ou montar em um host alternativo.

** Operações de backup, restauração, clone, montagem, desmontagem, catálogo, descatálogo e verificação são compatíveis com o hardware NVMe, exceto para ambientes virtualizados como RDM.
+
As operações acima são suportadas em dispositivos sem partições ou com partição única.

+

NOTE: Você pode configurar a solução multipathing para dispositivos NVMe definindo a opção multipathing nativa no kernel. O multipathing do Mapeador de dispositivos (DM) não é suportado.

** Workflows de backup, restauração, clone, montar, desmontar, catalogar, descatalogar e verificar workflows são compatíveis com NVMe em TCP/IP.
** Workflows de backup, restauração, clone, montar, desmontar, catalogar, descatalogar e verificar são compatíveis com o layout VMDK criado no NVMe sobre TCP/IP.


* É compatível com a sincronização ativa do SnapMirror (lançada inicialmente como SnapMirror Business Continuity [SM-BC]), que permite que os serviços empresariais continuem operando mesmo em caso de falha completa do local, oferecendo suporte para failover transparente de aplicações usando uma cópia secundária. Nem a intervenção manual nem o script adicional são necessários para acionar um failover com a sincronização ativa do SnapMirror.
* Suporta qualquer usuário não padrão em vez de oracle e Grid.
+
Para oferecer suporte aos usuários não padrão, você deve definir os usuários não padrão modificando os valores dos parâmetros no arquivo *sco.properties* localizado em _file /var/opt/SnapCenter/SCO/etc/_.

+
Os valores padrão dos parâmetros são definidos como oracle e Grid.

+
** DB_USER: oracle
** DB_GROUP
** GI_USER_grid
** GI_GROUP: Instalação



