---
permalink: protect-sco/task_define_a_backup_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: Definir uma estratégia de backup garante que você tenha os meios para restaurar ou clonar com sucesso seus bancos de dados. 
---
= Definir uma estratégia de backup para bancos de dados Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Defina uma estratégia de backup para garantir que você tenha os meios de restaurar ou clonar com sucesso seus bancos de dados.

Seu contrato de nível de serviço (SLA), objetivo de tempo de recuperação (rto) e objetivo do ponto de restauração (RPO) determinam em grande parte a sua estratégia de backup.

* O SLA define o nível de serviço esperado e aborda questões relacionadas ao serviço, como a disponibilidade e o desempenho do serviço.
* O rto define o tempo em que um processo de negócios deve ser restaurado após uma interrupção no serviço.
* RPO define a idade dos arquivos que devem ser recuperados do armazenamento de backup para que as operações regulares sejam retomadas após uma falha.




== Configurações de banco de dados Oracle compatíveis para backups

O SnapCenter suporta backup de diferentes configurações de banco de dados Oracle.

* Oracle Standalone
* Oracle Real Application clusters (RAC)
* Oracle Standalone Legacy
* Oracle Standalone Container Database (CDB)
* Espera do Oracle Data Guard
+
Você só pode criar backups de montagem offline de bancos de dados em espera do Data Guard. Backup off-line-shutdown, backup somente de log de arquivamento e backup completo não são suportados.

* Espera do Oracle ative Data Guard
+
Você só pode criar backups online de bancos de dados em espera do ative Data Guard. O backup e o backup completo somente de log de arquivamento não são suportados.

+

NOTE: Antes de criar um backup do banco de dados de espera do Data Guard ou do ative Data Guard, o processo de recuperação gerenciado (MRP) é interrompido e, uma vez que o backup é criado, o MRP é iniciado.

* Gerenciamento automático de storage (ASM)
+
** ASM autônomo e ASM RAC no Virtual Machine Disk (VMDK)
+

NOTE: Entre todos os métodos de restauração suportados para bancos de dados Oracle, você pode executar apenas a restauração de conexão e cópia de bancos de dados ASM RAC no VMDK.

** ASM Standalone e ASM RAC no RDM (Raw Device mapping) você pode executar operações de backup, restauração e clone em bancos de dados Oracle no ASM, com ou sem ASMLib.
** Controlador de filtro Oracle ASM (ASMFD)
+

NOTE: As operações de migração PDB e clonagem PDB não são suportadas.

** Oracle Flex ASM




Para obter as informações mais recentes sobre versões Oracle suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].



== Tipos de backup suportados para bancos de dados Oracle

Tipo de backup especifica o tipo de backup que você deseja criar. O SnapCenter suporta tipos de backup on-line e off-line para bancos de dados Oracle.



=== Backup on-line

Um backup que é criado quando o banco de dados está no estado on-line é chamado de backup on-line. Também chamado de hot backup, um backup on-line permite que você crie um backup do banco de dados sem desligá-lo.

Como parte do backup on-line, você pode criar um backup dos seguintes arquivos:

* Arquivos de dados e controle somente arquivos
* Arquivar apenas ficheiros de registo (a base de dados não é colocada no modo de cópia de segurança neste cenário)
* Banco de dados completo que inclui arquivos de dados, arquivos de controle e arquivos de log de arquivamento




=== Cópia de segurança offline

Um backup criado quando o banco de dados está em um estado montado ou desligado é chamado de backup off-line. Um backup off-line também é chamado de backup frio. Você pode incluir somente arquivos de dados e arquivos de controle em backups offline. Você pode criar um backup de montagem off-line ou de desligamento off-line.

* Ao criar um backup de montagem off-line, você deve garantir que o banco de dados esteja em um estado montado.
+
Se o banco de dados estiver em qualquer outro estado, a operação de backup falhará.

* Ao criar um backup de desligamento off-line, o banco de dados pode estar em qualquer estado.
+
O estado da base de dados é alterado para o estado necessário para criar uma cópia de segurança. Depois de criar a cópia de segurança, o estado da base de dados é revertido para o estado original.





== Como o SnapCenter descobre bancos de dados Oracle

"Recursos" são bancos de dados Oracle no host que são mantidos pelo SnapCenter. Você pode adicionar esses bancos de dados a grupos de recursos para executar operações de proteção de dados depois de descobrir os bancos de dados disponíveis. Você deve estar ciente do processo que o SnapCenter segue para descobrir diferentes tipos e versões de bancos de dados Oracle.

|===
| Para versões Oracle 11__g__ a 12__c__R1 | Para versões Oracle 12__c__R2 a 18__c__ 


 a| 
*Base de dados RAC*: Os bancos de dados RAC são descobertos apenas com base em entradas /etc/oratab.

Você deve ter as entradas do banco de dados no arquivo /etc/oratab.
 a| 
*Base de dados RAC*: Os bancos de dados RAC são descobertos usando o comando srvctl config.



 a| 
*Standalone*: Os bancos de dados autônomos são descobertos apenas com base em entradas /etc/oratab.

Você deve ter as entradas do banco de dados no arquivo /etc/oratab.
 a| 
*Standalone*: Os bancos de dados autônomos são descobertos com base nas entradas no arquivo /etc/oratab e na saída do comando srvctl config.



 a| 
*ASM*: A entrada de instância ASM deve estar disponível no arquivo /etc/oratab.
 a| 
*ASM*: A entrada de instância ASM não precisa estar no arquivo /etc/oratab.



 a| 
*RAC One Node*: Os bancos de dados RAC One Node são descobertos apenas com base em entradas /etc/oratab.

Os bancos de dados devem estar no estado _nomount_, _mount_ ou _open_. Você deve ter as entradas do banco de dados no arquivo /etc/oratab.

O status do banco de dados RAC One Node será marcado como renomeado ou excluído se o banco de dados já estiver descoberto e os backups estiverem associados ao banco de dados.

Você deve executar as seguintes etapas se o banco de dados for realocado:

. Adicione manualmente a entrada do banco de dados realocada no arquivo /etc/oratab no nó RAC com falha.
. Atualizar manualmente os recursos.
. Selecione o banco de dados RAC One Node na página de recursos e clique em *Configurações do banco de dados*.
. Configure o banco de dados para definir os nós de cluster preferidos para o nó RAC que hospeda o banco de dados atualmente.
. Execute as operações do SnapCenter.



NOTE: Se você tiver relocado um banco de dados de um nó para outro nó e se a entrada do oratab no nó anterior não for excluída, exclua manualmente a entrada do oratab para evitar que o mesmo banco de dados seja exibido duas vezes.
 a| 
*RAC One Node*: Os bancos de dados RAC One Node são descobertos usando apenas o comando srvctl config.

Os bancos de dados devem estar no estado _nomount_, _mount_ ou _open_. O status do banco de dados RAC One Node será marcado como renomeado ou excluído se o banco de dados já estiver descoberto e os backups estiverem associados ao banco de dados.

Você deve executar as seguintes etapas se o banco de dados for realocado:

. Atualizar manualmente os recursos.
. Selecione o banco de dados RAC One Node na página de recursos e clique em **Configurações de banco de dados**.
. Configure o banco de dados para definir os nós de cluster preferidos para o nó RAC que hospeda o banco de dados atualmente.
. Execute as operações do SnapCenter.


|===

NOTE: Se houver alguma entrada de banco de dados Oracle 12__c__R2 e 18__c___ no arquivo /etc/oratab e o mesmo banco de dados estiver registrado com o comando srvctl config, o SnapCenter eliminará as entradas duplicadas do banco de dados. Se houver entradas de banco de dados obsoletas, o banco de dados será descoberto, mas o banco de dados será inacessível e o status será off-line.



== Nós preferenciais na configuração RAC

Na configuração do Oracle Real Application clusters (RAC), você pode especificar os nós preferenciais nos quais a operação de backup será executada. Se você não especificar o nó preferido, o SnapCenter atribuirá automaticamente um nó como o nó preferido e o backup será criado nesse nó.

Os nós preferidos podem ser um ou todos os nós de cluster onde as instâncias de banco de dados RAC estão presentes. A operação de backup será acionada somente nesses nós preferenciais na ordem da preferência.

Exemplo: O banco de dados RAC cdbrac tem três instâncias: cdbrac1 em node1, cdbrac2 em node2 e cdbrac3 em node3. As instâncias node1 e node2 são configuradas para serem os nós preferidos, com node2 como a primeira preferência e node1 como a segunda preferência. Quando você executa uma operação de backup, a operação é tentada pela primeira vez no node2 porque é o primeiro nó preferido. Se o node2 não estiver no estado para fazer backup, o que pode ser devido a vários motivos, como o agente plug-in não está sendo executado no host, a instância do banco de dados no host não está no estado necessário para o tipo de backup especificado, ou a instância do banco de dados no node2 em uma configuração FlexASM não está sendo servida pela instância local ASM; então a operação será tentada no node1. O node3 não será usado para backup porque não está na lista de nós preferenciais.

Em uma configuração do Flex ASM, os Leaf Nodes não serão listados como nós preferenciais se a cardinalidade for menor que os nós numéricos no cluster RAC. Se houver alguma alteração nas funções de nó de cluster do Flex ASM, você deverá descobrir manualmente para que os nós preferidos sejam atualizados.



=== Estado da base de dados necessário

As instâncias do banco de dados RAC nos nós preferenciais devem estar no estado necessário para que o backup seja concluído com êxito:

* Uma das instâncias do banco de dados RAC nos nós preferenciais configurados deve estar no estado aberto para criar um backup on-line.
* Uma das instâncias do banco de dados RAC nos nós preferenciais configurados deve estar no estado de montagem e todas as outras instâncias, incluindo outros nós preferenciais, devem estar no estado de montagem ou inferiores para criar um backup de montagem off-line.
* As instâncias de banco de dados RAC podem estar em qualquer estado, mas você deve especificar os nós preferenciais para criar um backup de desligamento off-line.




== Como catalogar backups com o Oracle Recovery Manager

Os backups dos bancos de dados Oracle podem ser catalogados com o Oracle Recovery Manager (RMAN) para armazenar as informações de backup no repositório Oracle RMAN.

Os backups catalogados podem ser usados posteriormente para restauração em nível de bloco ou operações de recuperação de ponto no tempo de tablespace. Quando você não precisa desses backups catalogados, você pode remover as informações do catálogo.

O banco de dados deve estar em estado montado ou superior para catalogação. Você pode fazer catalogação em backups de dados, backups de log de arquivamento e backups completos. Se a catalogação estiver ativada para um backup de um grupo de recursos que tenha vários bancos de dados, a catalogação é realizada para cada banco de dados. Para bancos de dados Oracle RAC, a catalogação será realizada no nó preferido onde o banco de dados está, pelo menos, no estado montado.


NOTE: Se você quiser catalogar backups de um banco de dados RAC, verifique se nenhum outro trabalho está sendo executado para esse banco de dados. Se outro trabalho estiver em execução, a operação de catalogação falhará em vez de ficar na fila.

Por padrão, o arquivo de controle de banco de dados de destino é usado para catalogação. Se você quiser adicionar um banco de dados de catálogo externo, você pode configurá-lo especificando o nome do substrato de rede transparente (TNS) e credencial do catálogo externo usando o assistente Configurações de banco de dados da interface gráfica do usuário (GUI) do SnapCenter. Você também pode configurar o banco de dados de catálogo externo da CLI executando o comando Configure-SmOracleDatabase com as opções -OracleRmanCatalogCredentialName e -OracleRmanCatalogTnsName.

Se você ativou a opção catalogação ao criar uma política de backup Oracle a partir da GUI do SnapCenter, os backups serão catalogados usando o Oracle RMAN como parte da operação de backup. Você também pode executar catalogação diferida de backups executando o comando Catalog-SmBackupWithOracleRMAN. Depois de catalogar os backups, você pode executar o comando Get-SmBackupDetails para obter as informações de backup catalogadas, como a tag para datafiles catalogados, o caminho do catálogo do arquivo de controle e os locais de log do arquivo catalogado.

Se o nome do grupo de discos ASM for maior ou igual a 16 carateres, a partir do SnapCenter 3,0, o formato de nomenclatura usado para o backup é SC_HASHCODEofDISKGROUP_DBSID_BACKUPID. No entanto, se o nome do grupo de discos for inferior a 16 carateres, o formato de nomenclatura usado para o backup é DISKGROUPNAME_DBSID_BACKUPID, que é o mesmo formato usado no SnapCenter 2,0.


NOTE: O HASHCODEofDISKGROUP é um número gerado automaticamente (2 a 10 dígitos) exclusivo para cada grupo de discos ASM.

Você pode executar verificações cruzadas para atualizar informações do repositório RMAN desatualizadas sobre backups cujos Registros do repositório não correspondem ao seu status físico. Por exemplo, se um usuário remover logs arquivados do disco com um comando do sistema operacional, o arquivo de controle ainda indica que os logs estão no disco, quando na verdade eles não estão. A operação de verificação cruzada permite-lhe atualizar o ficheiro de controlo com as informações. Você pode ativar a verificação cruzada executando o comando Set-SmConfigSettings e atribuindo o valor TRUE ao parâmetro ENABLE_CROSSCHECK. O valor padrão é definido como FALSE.

`sccli Set-SmConfigSettings-ConfigSettingsTypePlugin-PluginCodeSCO-ConfigSettings "KEY=ENABLE_CROSSCHECK, VALUE=TRUE"`

Você pode remover as informações do catálogo executando o comando Uncatalog-SmBackupWithOracleRMAN. Não é possível remover as informações do catálogo usando a GUI do SnapCenter. No entanto, as informações de um backup catalogado são removidas ao excluir o backup ou ao excluir o grupo de retenção e recursos associado ao backup catalogado.


NOTE: Quando você força uma exclusão do host SnapCenter, as informações dos backups catalogados associados a esse host não são removidas. Você deve remover informações de todos os backups catalogados para esse host antes de forçar a exclusão do host.

Se a catalogação e a descatalogação falharem porque o tempo de operação excedeu o valor de tempo limite especificado para o parâmetro ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT, você deve modificar o valor do parâmetro executando o seguinte comando:

`/opt/Netapp/snapcenter/spl/bin/sccli Set-SmConfigSettings-ConfigSettingsType Plugin -PluginCode SCO-ConfigSettings "KEY=ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT,VALUE=user_defined_value"`

Depois de modificar o valor do parâmetro, reinicie o serviço SnapCenter Plug-in Loader (SPL) executando o seguinte comando:

`/opt/NetApp/snapcenter/spl/bin/spl restart`

As informações sobre os parâmetros que podem ser usados com o comando e suas descrições podem ser obtidas executando get-Help command_name. Em alternativa, pode também consultar o https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["Guia de Referência de comandos do software SnapCenter"^].



== Fazer backup de programações

A frequência de backup (tipo de agendamento) é especificada em políticas; uma programação de backup é especificada na configuração do grupo de recursos. O fator mais crítico na determinação de uma frequência ou programação de backup é a taxa de alteração do recurso e a importância dos dados. Você pode fazer backup de um recurso muito usado a cada hora, enquanto você pode fazer backup de um recurso raramente usado uma vez por dia. Outros fatores incluem a importância do recurso para a sua organização, seu Contrato de nível de Serviço (SLA) e seu objetivo de ponto de recuperação (RPO).

Um SLA define o nível de serviço esperado e aborda muitos problemas relacionados ao serviço, incluindo a disponibilidade e o desempenho do serviço. Um RPO define a estratégia para a era dos arquivos que precisam ser recuperados do storage de backup para que as operações regulares sejam retomadas após uma falha. O SLA e o RPO contribuem para a estratégia de proteção de dados.

Mesmo para um recurso muito usado, não é necessário executar um backup completo mais de uma ou duas vezes por dia. Por exemplo, backups regulares de log de transações podem ser suficientes para garantir que você tenha os backups necessários. Quanto mais você fizer backup de seus bancos de dados, menos Registros de transações que o SnapCenter precisa usar no momento da restauração, o que pode resultar em operações de restauração mais rápidas.

Os programas de backup têm duas partes, como segue:

* Frequência de backup
+
A frequência de backup (com que frequência os backups devem ser executados), chamada _schedule type_ para alguns plug-ins, faz parte de uma configuração de política. Você pode selecionar a frequência de backup da política por hora, dia, semanal ou mensal. Se você não selecionar nenhuma dessas frequências, a política criada será uma política somente sob demanda. Você pode acessar políticas clicando em *Configurações* > *políticas*.

* Fazer backup de programações
+
As agendas de backup (exatamente quando os backups devem ser executados) fazem parte de uma configuração de grupo de recursos. Por exemplo, se você tiver um grupo de recursos que tenha uma política configurada para backups semanais, poderá configurar a programação para fazer backup todas as quintas-feiras às 10:00 horas. Você pode acessar programações de grupos de recursos clicando em *recursos* > *grupos de recursos*.





== Convenções de nomenclatura de backup

Você pode usar a convenção padrão de nomenclatura Snapshot ou usar uma convenção de nomenclatura personalizada. A convenção de nomenclatura de backup padrão adiciona um carimbo de data/hora aos nomes de Snapshot que ajuda a identificar quando as cópias foram criadas.

O Snapshot usa a seguinte convenção de nomenclatura padrão:

`resourcegroupname_hostname_timestamp`

Você deve nomear seus grupos de recursos de backup logicamente, como no exemplo a seguir:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
Neste exemplo, os elementos de sintaxe têm os seguintes significados:

* _dts1_ é o nome do grupo de recursos.
* _mach1x88_ é o nome do host.
* _03-12-2015_23.17.26_ é a data e o carimbo de data/hora.


Como alternativa, você pode especificar o formato do nome da captura Instantânea enquanto protege recursos ou grupos de recursos selecionando *usar formato de nome personalizado para cópia Instantânea*. Por exemplo, customtext_resourcegroup_policy_hostname ou resourcegroup_hostname. Por padrão, o sufixo do carimbo de hora é adicionado ao nome do instantâneo.



== Opções de retenção de backup

Você pode escolher o número de dias para os quais reter cópias de backup ou especificar o número de cópias de backup que deseja reter, até um máximo de ONTAP de 255 cópias. Por exemplo, sua organização pode exigir que você retenha 10 dias de cópias de backup ou 130 cópias de backup.

Ao criar uma política, você pode especificar as opções de retenção para o tipo de backup e o tipo de agendamento.

Se você configurar a replicação do SnapMirror, a política de retenção será espelhada no volume de destino.

O SnapCenter exclui os backups retidos que têm rótulos de retenção que correspondem ao tipo de agendamento. Se o tipo de agendamento tiver sido alterado para o grupo de recursos ou recursos, os backups com o rótulo de tipo de agendamento antigo ainda poderão permanecer no sistema.


NOTE: Para retenção de longo prazo de cópias de backup, você deve usar o backup SnapVault.



== Verifique a cópia de backup usando o volume de storage primário ou secundário

É possível verificar cópias de backup no volume de storage primário ou no volume de storage secundário SnapMirror ou SnapVault. A verificação usando um volume de storage secundário reduz a carga no volume de storage primário.

Quando você verifica um backup que está no volume de storage primário ou secundário, todos os snapshots primário e secundário são marcados como verificados.

A licença SnapRestore é necessária para verificar cópias de backup no volume de storage secundário SnapMirror e SnapVault.
