---
permalink: protect-sce/concept_requirements_for_restoring_an_exchange_database.html 
sidebar: sidebar 
keywords: restoring an Exchange database 
summary: Antes de restaurar um banco de dados do Exchange Server a partir de um plug-in do SnapCenter para backup do Microsoft Exchange Server, você deve garantir que vários requisitos sejam atendidos. 
---
= Requisitos para restaurar um banco de dados do Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de restaurar um banco de dados do Exchange Server a partir de um plug-in do SnapCenter para backup do Microsoft Exchange Server, você deve garantir que vários requisitos sejam atendidos.


NOTE: Para usar completamente a funcionalidade de restauração, você deve atualizar o servidor SnapCenter e o plug-in SnapCenter para o banco de dados Exchange para 4,6.

* O Exchange Server deve estar on-line e em execução antes de poder restaurar um banco de dados.
* Os bancos de dados devem existir no Exchange Server.
+

NOTE: Restaurar bancos de dados excluídos não é suportado.

* As programações do SnapCenter para o banco de dados devem ser suspensas.
* O servidor SnapCenter e o plug-in do SnapCenter para o host do Microsoft Exchange Server devem estar conetados ao storage primário e secundário que contém os backups que você deseja restaurar.

