---
permalink: protect-sce/reference_prerequisites_to_add_hosts_and_install_snapcenter_plug_in_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server 
summary: Antes de adicionar um host e instalar os pacotes de plug-in, você deve completar todos os requisitos. 
---
= Pré-requisitos para adicionar hosts e instalar o plug-in do SnapCenter para Microsoft Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de adicionar um host e instalar os pacotes de plug-in, você deve completar todos os requisitos.

* Se estiver a utilizar iSCSI, o serviço iSCSI tem de estar em execução.
* Você deve ter um usuário de domínio com Privileges de administrador local com permissões de login local no host remoto.
* Você deve estar usando o Microsoft Exchange Server 2013, 2016 ou 2019 para configurações autônomas e do grupo de disponibilidade de banco de dados.
* Ao instalar um plug-in em um host do Windows, se você especificar uma credencial que não está integrada ou se o usuário pertence a um usuário local do grupo de trabalho, será necessário desativar o UAC no host.
* Se você gerenciar nós de cluster no SnapCenter, precisará ter um usuário com Privileges administrativo para todos os nós do cluster.
* Você deve ter um usuário com permissões administrativas no Exchange Server.
* Se o SnapManager para Microsoft Exchange Server e o SnapDrive para Windows já estiverem instalados, você deve cancelar o Registro do provedor de hardware VSS usado pelo SnapDrive para Windows antes de instalar o plug-in para Exchange no mesmo Exchange Server para garantir a proteção de dados bem-sucedida usando o SnapCenter.
* Se o SnapManager for Microsoft Exchange Server e o Plug-in for Exchange estiverem instalados no mesmo servidor, você deverá suspender ou excluir do agendador do Windows todas as programações criadas pelo SnapManager para o Microsoft Exchange Server.
* O host deve ser resolvido para o nome de domínio totalmente qualificado (FQDN) do servidor. Se o arquivo hosts for modificado para torná-lo resoluvel e se o nome curto e o FQDN forem especificados no arquivo hosts, crie uma entrada no arquivo SnapCenter hosts no seguinte formato: _<ip_address> <host_fqdn> <host_name>_.
* Certifique-se de que as seguintes portas não estão bloqueadas no firewall, caso contrário, a operação de adição de host falha. Para resolver esse problema, você deve configurar o intervalo de portas dinâmicas. Para obter mais informações, https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-rpc-dynamic-port-allocation-with-firewalls["Documentação da Microsoft"^]consulte .
+
** Intervalo de portas 50000 - 51000 para Windows 2016 e Exchange 2016
** Intervalo de portas 6000 - 6500 para Windows 2012 R2 e Exchange 2013
** Intervalo de portas 49152 - 65536 para Windows 2019




[NOTE]
====
Para identificar o intervalo de portas, execute os seguintes comandos:

* netsh int ipv4 mostra dínyicport tcp
* netsh int ipv4 show dynamicport udp
* netsh int ipv6 mostra dínyicport tcp
* netsh int ipv6 show dynamicport udp


====


== Requisitos de host para instalar o pacote de plug-ins do SnapCenter para Windows

Antes de instalar o pacote de plug-ins do SnapCenter para Windows, você deve estar familiarizado com alguns requisitos básicos de espaço do sistema host e requisitos de dimensionamento.

|===
| Item | Requisitos 


 a| 
Sistemas operacionais
 a| 
Microsoft Windows

Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].



 a| 
RAM mínima para o plug-in SnapCenter no host
 a| 
1 GB



 a| 
Espaço mínimo de instalação e log para o plug-in SnapCenter no host
 a| 
5 GB


NOTE: Deve alocar espaço em disco suficiente e monitorizar o consumo de armazenamento pela pasta de registos. O espaço de registo necessário varia consoante o número de entidades a proteger e a frequência das operações de proteçãoão de dados. Se não houver espaço em disco suficiente, os logs não serão criados para as operações executadas recentemente.



 a| 
Pacotes de software necessários
 a| 
* .NET Core 8.0.5
* PowerShell Core 7.4.2
* Java 11 Oracle Java e OpenJDK


Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].

Para obter informações específicas de solução de problemas .NET, consulte https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["A atualização ou instalação do SnapCenter falha para sistemas legados que não têm conetividade com a Internet."]

|===


== É necessário o Exchange Server Privileges

Para permitir que o SnapCenter adicione o Exchange Server ou DAG e instale o plug-in do SnapCenter para o Microsoft Exchange Server em um host ou DAG, você deve configurar o SnapCenter com credenciais para um usuário com um conjunto mínimo de Privileges e permissões.

Você deve ter um usuário de domínio com o administrador local Privileges e com permissões de login local no host remoto do Exchange, bem como permissões administrativas em todos os nós no DAG. O usuário do domínio requer as seguintes permissões mínimas:

* Add-MailboxDatabaseCopy
* Desmontar a base de dados
* Get-AdServerSettings
* Get-DatabaseAvailabilityGroup
* Get-ExchangeServer
* Get-MailboxDatabase
* Get-MailboxDatabaseCopyStatus
* Get-MailboxServer
* Get-MailboxStatistics
* Get-PublicFolderDatabase
* Mover-ActiveMailboxDatabase
* Move-DatabasePath -ConfigurationOnly: True
* Monte-base de dados
* New-MailboxDatabase
* New-PublicFolderDatabase
* Remover-MailboxDatabase
* Remove-MailboxDatabaseCopy
* Remover-PublicFolderDatabase
* Resume-MailboxDatabaseCopy
* Set-AdServerSettings
* Set-MailboxDatabase -allowfilerestore: Verdadeiro
* Set-MailboxDatabaseCopy
* Set-PublicFolderDatabase
* Suspend-MailboxDatabaseCopy
* Update-MailboxDatabaseCopy




== Requisitos de host para instalar o pacote de plug-ins do SnapCenter para Windows

Antes de instalar o pacote de plug-ins do SnapCenter para Windows, você deve estar familiarizado com alguns requisitos básicos de espaço do sistema host e requisitos de dimensionamento.

|===
| Item | Requisitos 


 a| 
Sistemas operacionais
 a| 
Microsoft Windows

Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].



 a| 
RAM mínima para o plug-in SnapCenter no host
 a| 
1 GB



 a| 
Espaço mínimo de instalação e log para o plug-in SnapCenter no host
 a| 
5 GB


NOTE: Deve alocar espaço em disco suficiente e monitorizar o consumo de armazenamento pela pasta de registos. O espaço de registo necessário varia consoante o número de entidades a proteger e a frequência das operações de proteçãoão de dados. Se não houver espaço em disco suficiente, os logs não serão criados para as operações executadas recentemente.



 a| 
Pacotes de software necessários
 a| 
* .NET Core 8.0.5
* PowerShell Core 7.4.2
* Java 11 Oracle Java e OpenJDK


Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].

Para obter informações específicas de solução de problemas .NET, consulte https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["A atualização ou instalação do SnapCenter falha para sistemas legados que não têm conetividade com a Internet."]

|===