---
permalink: protect-sce/task_install_the_snapcenter_plug_in_for_exchange_silently_from_the_command_line.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Você deve instalar o plug-in para o Exchange a partir da interface de usuário do SnapCenter. No entanto, se você não puder por algum motivo, você pode executar o programa de instalação Plug-in para Exchange sem supervisão no modo silencioso a partir da linha de comando do Windows. 
---
= Instale o plug-in SnapCenter para Exchange silenciosamente a partir da linha de comando
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar o plug-in para o Exchange a partir da interface de usuário do SnapCenter. No entanto, se você não puder por algum motivo, você pode executar o programa de instalação Plug-in para Exchange sem supervisão no modo silencioso a partir da linha de comando do Windows.

.Antes de começar
* Você deve ter feito backup de seus recursos do Microsoft Exchange Server.
* Você deve ter instalado os pacotes plug-in do SnapCenter.
* Você deve excluir a versão anterior do plug-in do SnapCenter para Microsoft SQL Server antes de instalar.
+
Para obter mais informações, https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["Como instalar um plug-in do SnapCenter manualmente e diretamente do host do plug-in"^]consulte .



.Passos
. Valide se a pasta _C: /Temp_ existe no host do plug-in e o usuário conetado tem acesso total a ela.
. Faça o download do plug-in do SnapCenter para o Microsoft Windows a partir do repositório _C:/ProgramData/NetApp/SnapCenter/Package_.
+
Este caminho é acessível a partir do host onde o servidor SnapCenter está instalado.

. Copie o arquivo de instalação para o host no qual você deseja instalar o plug-in.
. Em um prompt de comando do Windows no host local, navegue até o diretório para o qual você salvou os arquivos de instalação do plug-in.
. Digite o seguinte comando para instalar o plug-in.
+
_SnapCenter_Windows_host_plugin.exe"/Silent /debuglog"<Debug_Log_Path>" /log"<Log_Path>" BI_SnapCenter_PORT_<Num> SUITE_INSTALLDIR"<Install_Directory_Path>" BI_SERVICEACCOUNT <domain\administrator> BI_SERVICEPWD_<password>

+
Por exemplo:

+
NetApp: SnapCenter_Windows_host_plugin.exe"/silent /debuglog"C: HPPW_SCSQL_Install.log" /log"C: Temp" BI_SnapCenter_PORT_8145 SUITE_INSTALLDIR"C: SnapCenter NetApp_SnapCenter

+

NOTE: Todos os parâmetros passados durante a instalação do Plug-in para Exchange são sensíveis a maiúsculas e minúsculas.

+
Insira os seguintes valores para as variáveis:

+
|===
| Variável | Valor 


 a| 
_/debuglog"<Debug_Log_Path>_
 a| 
Especifique o nome e o local do arquivo de log do instalador do pacote, como no exemplo a seguir:

_Setup.exe /debuglog"C: PathToLog.setupexe.log_



 a| 
PORTA_BI_SnapCenter
 a| 
Especifique a porta na qual o SnapCenter se comunica com o SMCore.



 a| 
SUITE_INSTALLDIR
 a| 
Especifique o diretório de instalação do pacote de plug-in do host.



 a| 
BI_SERVICEACCOUNT
 a| 
Especifique o plug-in do SnapCenter para a conta de serviço da Web do Microsoft Windows.



 a| 
BI_SERVICEPWD
 a| 
Especifique a senha do plug-in do SnapCenter para a conta do serviço da Web do Microsoft Windows.



 a| 
ISFeatureInstall
 a| 
Especifique a solução a ser implantada pelo SnapCenter em host remoto.

|===
. Monitore o agendador de tarefas do Windows, o arquivo de log de instalação principal _C: Installdebug.log_ e os arquivos de instalação adicionais em _C: Temp_.
. Monitore o diretório _%temp%_ para verificar se os instaladores _msiexe.exe_ estão instalando o software sem erros.
+

NOTE: A instalação do plug-in para Exchange Registra o plug-in no host e não no servidor SnapCenter. Você pode Registrar o plug-in no servidor SnapCenter adicionando o host usando a GUI do SnapCenter ou cmdlet do PowerShell. Depois que o host é adicionado, o plug-in é descoberto automaticamente.


