---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter. Você deve criar credenciais para instalar o pacote de plug-ins e credenciais adicionais para executar operações de proteção de dados em bancos de dados. 
---
= Configurar credenciais para o plug-in SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter. Você deve criar credenciais para instalar o pacote de plug-ins e credenciais adicionais para executar operações de proteção de dados em bancos de dados.

.Sobre esta tarefa
Você deve configurar credenciais para instalar plug-ins em hosts do Windows. Embora você possa criar credenciais para o Windows depois de implantar hosts e instalar plug-ins, a prática recomendada é criar credenciais após adicionar SVMs, antes de implantar hosts e instalar plug-ins.

Configure as credenciais com o administrador Privileges, incluindo direitos de administrador no host remoto.

Se você configurar credenciais para grupos de recursos individuais e o nome de usuário não tiver Privileges de administrador completo, será necessário atribuir pelo menos o grupo de recursos e Privileges de backup ao nome de usuário.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credential*.
. Clique em *novo*.
+
É apresentada a janela Credential (credencial).

. Na página Credential (credencial), faça o seguinte:
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Introduza um nome para a credencial.



 a| 
Nome de utilizador
 a| 
Introduza o nome de utilizador utilizado para autenticação.

** Administrador de domínio ou qualquer membro do grupo de administradores
+
Especifique o administrador do domínio ou qualquer membro do grupo de administradores no sistema no qual você está instalando o plug-in do SnapCenter. Formatos válidos para o campo Nome de usuário são:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrador local (apenas para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local incorporado no sistema no qual você está instalando o plug-in SnapCenter. Você pode especificar uma conta de usuário local que pertence ao grupo de administradores locais se a conta de usuário tiver Privileges elevado ou o recurso de controle de acesso do usuário estiver desativado no sistema host. O formato válido para o campo Nome de usuário é: `UserName`





 a| 
Palavra-passe
 a| 
Introduza a palavra-passe utilizada para autenticação.



 a| 
Autenticação
 a| 
Selecione Windows como o modo de autenticação.

|===
. Clique em *OK*.

