---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: Você deve estar ciente de certos requisitos de instalação antes de instalar o plug-in para Windows. 
---
= Requisitos de instalação para o plug-in SnapCenter para Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente de certos requisitos de instalação antes de instalar o plug-in para Windows.

Antes de começar a usar o plug-in para Windows, o administrador do SnapCenter deve instalar e configurar o servidor SnapCenter e executar tarefas pré-requisitos.

* Você deve ter o SnapCenter admin Privileges para instalar o plug-in para Windows.
+
A função de administrador do SnapCenter deve ter admin Privileges.

* Você deve ter instalado e configurado o servidor SnapCenter.
* Ao instalar um plug-in em um host do Windows, se você especificar uma credencial que não está integrada ou se o usuário pertence a um usuário local do grupo de trabalho, será necessário desativar o UAC no host.
* Você deve configurar o SnapMirror e o SnapVault se quiser replicação de backup.




== Requisitos de host para instalar o pacote de plug-ins do SnapCenter para Windows

Antes de instalar o pacote de plug-ins do SnapCenter para Windows, você deve estar familiarizado com alguns requisitos básicos de espaço do sistema host e requisitos de dimensionamento.

|===
| Item | Requisitos 


 a| 
Sistemas operacionais
 a| 
Microsoft Windows

Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].

Se você estiver em uma configuração de cluster do Windows, também deverá instalar e configurar o Gerenciamento Remoto do Windows (WinRM).



 a| 
RAM mínima para o plug-in SnapCenter no host
 a| 
1 GB



 a| 
Espaço mínimo de instalação e log para o plug-in SnapCenter no host
 a| 
5 GB


NOTE: Deve alocar espaço em disco suficiente e monitorizar o consumo de armazenamento pela pasta de registos. O espaço de registo necessário varia consoante o número de entidades a proteger e a frequência das operações de proteçãoão de dados. Se não houver espaço em disco suficiente, os logs não serão criados para as operações executadas recentemente.



 a| 
Pacotes de software necessários
 a| 
* Pacote de Hospedagem ASP.NET Core Runtime 8.0.12 (e todos os patches 8,0.x subsequentes)
* PowerShell Core 7.4.2


Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].

Para obter informações específicas de solução de problemas .NET, consulte https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["A atualização ou instalação do SnapCenter falha para sistemas legados que não têm conetividade com a Internet."]

|===


== Configure suas credenciais para o plug-in para Windows

O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter. Você deve criar credenciais para a instalação de plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados em sistemas de arquivos do Windows.

*O que você vai precisar*

* Você deve configurar as credenciais do Windows antes de instalar os plug-ins.
* Você deve configurar as credenciais com o Privileges de administrador, incluindo direitos de administrador, no host remoto.
* Se você configurar credenciais para grupos de recursos individuais e o usuário não tiver Privileges de administrador completo, será necessário atribuir ao usuário pelo menos o grupo de recursos e Privileges de backup.


*Passos*

. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credential*.
. Clique em *novo*.
. Na página Credential (credencial), faça o seguinte:
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Introduza um nome para as credenciais.



 a| 
Nome de utilizador/Palavra-passe
 a| 
Introduza o nome de utilizador e a palavra-passe utilizados para autenticação.

** Administrador de domínio ou qualquer membro do grupo de administradores
+
Especifique o administrador do domínio ou qualquer membro do grupo de administradores no sistema no qual você está instalando o plug-in do SnapCenter. Os formatos válidos para o campo Nome de usuário são os seguintes:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`
*** `UserName@upn`


** Administrador local (apenas para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local incorporado no sistema no qual você está instalando o plug-in SnapCenter. Você pode especificar uma conta de usuário local que pertence ao grupo de administradores locais se a conta de usuário tiver Privileges elevado ou o recurso de controle de acesso do usuário estiver desativado no sistema host. O formato válido para o campo Nome de usuário é o seguinte: `UserName`

+
Não use aspas duplas (") ou backtick (') nas senhas. Você não deve usar os símbolos menos de (>) e exclamação (!) juntos em senhas. Por exemplo, lessthan!10, lessthan10You!, backtick'12.





 a| 
Palavra-passe
 a| 
Introduza a palavra-passe utilizada para autenticação.

|===
. Clique em *OK*.
+
Depois de concluir a configuração das credenciais, talvez você queira atribuir a manutenção de credenciais a um usuário ou grupo de usuários na página Usuário e Acesso.





== Configure o gMSA no Windows Server 2016 ou posterior

O Windows Server 2016 ou posterior permite criar uma conta de serviço gerenciado de grupo (gMSA) que fornece gerenciamento automatizado de senha de conta de serviço a partir de uma conta de domínio gerenciado.

.Antes de começar
* Você deve ter um controlador de domínio do Windows Server 2016 ou posterior.
* Você deve ter um host Windows Server 2016 ou posterior, que é um membro do domínio.


.Passos
. Crie uma chave raiz KDS para gerar senhas exclusivas para cada objeto em seu gMSA.
. Para cada domínio, execute o seguinte comando do controlador de domínio do Windows: Add-KDSRootKey -EffectiveImmediately
. Crie e configure seu gMSA:
+
.. Crie uma conta de grupo de usuários no seguinte formato:
+
 domainName\accountName$
.. Adicione objetos de computador ao grupo.
.. Use o grupo de usuários que você acabou de criar para criar o gMSA.
+
Por exemplo,

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. Execute `Get-ADServiceAccount` o comando para verificar a conta de serviço.


. Configure o gMSA em seus hosts:
+
.. Ative o módulo do ative Directory para Windows PowerShell no host onde você deseja usar a conta gMSA.
+
Para fazer isso, execute o seguinte comando do PowerShell:

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. Reinicie o host.
.. Instale o gMSA em seu host executando o seguinte comando a partir do prompt de comando do PowerShell: `Install-AdServiceAccount <gMSA>`
.. Verifique sua conta gMSA executando o seguinte comando: `Test-AdServiceAccount <gMSA>`


. Atribua o Privileges administrativo ao gMSA configurado no host.
. Adicione o host do Windows especificando a conta gMSA configurada no servidor SnapCenter.
+
O servidor SnapCenter instalará os plug-ins selecionados no host e o gMSA especificado será usado como a conta de logon de serviço durante a instalação do plug-in.


