---
permalink: protect-scw/task_determine_resource_availability_for_windows_file_systems.html 
sidebar: sidebar 
keywords: availability 
summary: Os recursos são os LUNs e componentes semelhantes no sistema de arquivos que são mantidos pelos plug-ins instalados. Você pode adicionar esses recursos a grupos de recursos para que você possa executar tarefas de proteção de dados em vários recursos, mas primeiro você deve identificar quais recursos você tem disponíveis. A descoberta de recursos disponíveis também verifica se a instalação do plug-in foi concluída com sucesso. 
---
= Determinar a disponibilidade de recursos para sistemas de arquivos do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os recursos são os LUNs e componentes semelhantes no sistema de arquivos que são mantidos pelos plug-ins instalados. Você pode adicionar esses recursos a grupos de recursos para que você possa executar tarefas de proteção de dados em vários recursos, mas primeiro você deve identificar quais recursos você tem disponíveis. A descoberta de recursos disponíveis também verifica se a instalação do plug-in foi concluída com sucesso.

.Antes de começar
* Você já deve ter concluído tarefas como instalar o servidor SnapCenter, adicionar hosts, criar conexões de máquina virtual de storage (SVM) e adicionar credenciais.
* Se os arquivos residirem em LUNs ou VMDKs do VMware RDM, você deverá implantar o plug-in do SnapCenter para VMware vSphere e Registrar o plug-in no SnapCenter. Para obter mais informações, https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Plug-in do SnapCenter para documentação do VMware vSphere"^]consulte .


.Passos
. No painel de navegação esquerdo, clique em *Resources* e selecione o plug-in apropriado na lista.
. Na página recursos, selecione *sistemas de arquivos* na lista.
. Selecione o host para filtrar a lista de recursos e clique em *Atualizar recursos*.
+
Os sistemas de arquivos recém-adicionados, renomeados ou excluídos são atualizados para o inventário do servidor SnapCenter.

+

IMPORTANT: Você deve atualizar os recursos se os bancos de dados forem renomeados fora do SnapCenter.


