---
permalink: concept/concept_prescripts_and_postscripts.html 
sidebar: sidebar 
keywords: prescript, postscript, script path, script timeout, script types supported 
summary: Você pode usar prescripts e postscripts personalizados como parte de suas operações de proteção de dados. Esses scripts habilitam a automação antes do trabalho de proteção de dados ou depois. Por exemplo, você pode incluir um script que o notifica automaticamente sobre falhas ou avisos de trabalhos de proteção de dados. Antes de configurar suas prescriptas e pós-scripts, você deve entender alguns dos requisitos para criar esses scripts. 
---
= Prescripts e postscripts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar prescripts e postscripts personalizados como parte de suas operações de proteção de dados. Esses scripts habilitam a automação antes do trabalho de proteção de dados ou depois. Por exemplo, você pode incluir um script que o notifica automaticamente sobre falhas ou avisos de trabalhos de proteção de dados. Antes de configurar suas prescriptas e pós-scripts, você deve entender alguns dos requisitos para criar esses scripts.



== Tipos de script suportados

Os seguintes tipos de scripts são suportados para o Windows:

* Arquivos em lote
* Scripts do PowerShell
* Scripts Perl


Os seguintes tipos de scripts são suportados para UNIX:

* Scripts Perl
* Scripts Python
* Scripts de shell
+

NOTE: Junto com shell bash padrão outros shells como sh-shell, k-shell e c-shell também são suportados.





== Caminho do script

Todos os prescripts e pós-scripts executados como parte das operações do SnapCenter, em sistemas de storage não virtualizados e virtualizados, são executados no host do plug-in.

* Os scripts do Windows devem estar localizados no host do plug-in.



NOTE: O caminho de prescripts ou postscripts não deve incluir unidades ou compartilhamentos. O caminho deve ser relativo ao SCRIPT_path.

* Os scripts UNIX devem estar localizados no host do plug-in.



NOTE: O caminho do script é validado no momento da execução.



== Onde especificar scripts

Os scripts são especificados nas políticas de backup. Quando um trabalho de backup é iniciado, a diretiva associa automaticamente o script aos recursos que estão sendo copiados. Ao criar uma política de backup, você pode especificar os argumentos prescritor e postscript.


NOTE: Não é possível especificar vários scripts.



== Tempos limite de script

O tempo limite é definido para 60 segundos, por padrão. Você pode modificar o valor de tempo limite.



== Saída de script

O diretório padrão para os arquivos de saída de prescripts e postscripts do Windows é o Windows System32.

Não há local padrão para as prescripts e postscripts UNIX. Você pode redirecionar o arquivo de saída para qualquer local preferido.
