---
permalink: concept/concept_disaster_recovery.html 
sidebar: sidebar 
keywords: Disaster Recovery 
summary: Você pode recuperar o servidor SnapCenter em caso de desastres como corrupção de recursos ou falha do servidor usando o recurso de recuperação de desastres do SnapCenter. 
---
= Recuperação de desastres do SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode recuperar o servidor SnapCenter em caso de desastres como corrupção de recursos ou falha do servidor usando o recurso recuperação de desastres (DR) do SnapCenter. Você pode recuperar o repositório do SnapCenter, as programações do servidor e os componentes de configuração do servidor. Você também pode recuperar o plug-in do SnapCenter para SQL Server e o plug-in do SnapCenter para armazenamento de dados SQL Server.

Esta seção descreve os dois tipos de recuperação de desastres (DR) no SnapCenter:

.DR do servidor SnapCenter
* Os dados do servidor SnapCenter são copiados e podem ser recuperados sem nenhum plug-in adicionado ou gerenciado pelo servidor SnapCenter.
* O servidor SnapCenter secundário deve ser instalado no mesmo diretório de instalação e na mesma porta que o servidor SnapCenter primário.
* Para autenticação multifator (MFA), durante o DR do servidor SnapCenter, feche todas as guias do navegador e reabra um navegador para fazer login novamente. Isso apagará os cookies de sessão existentes ou ativos e atualizará os dados de configuração corretos.
* A funcionalidade de recuperação de desastres do SnapCenter usa APIS REST para fazer backup do servidor SnapCenter. link:../tech-refresh/task_tech_refresh_server_host.html["Workflows de API REST para recuperação de desastres do servidor SnapCenter"]Consulte .
* O arquivo de configuração relacionado às configurações de auditoria não é feito backup no backup de DR e nem no servidor de DR após a operação de restauração. Deve repetir manualmente as definições do registo de auditoria.


.Plug-in do SnapCenter e recuperação de desastres de storage
O DR é compatível apenas com o plug-in SnapCenter para SQL Server. Quando o plug-in do SnapCenter estiver inativo, mude para um host SQL diferente e recupere os dados executando algumas etapas. link:../protect-scsql/task_disaster_recovery_scsql.html["Recuperação de desastres do plug-in SnapCenter para SQL Server"]Consulte .

A SnapCenter usa a tecnologia ONTAP SnapMirror para replicar dados. Ele pode ser usado para replicar dados para um local secundário para recuperação de desastres e mantê-los sincronizados. Um failover pode ser iniciado quebrando a relação de replicação no SnapMirror. Durante o failback, a sincronização pode ser revertida e os dados do local de DR podem ser replicados de volta para o local principal.
