---
permalink: protect-hana/concept_how_snapcenter_plug_in_for_sap_hana_database_uses_consistency_group_snapshot_copies.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: Você pode usar o plug-in para criar instantâneos de grupo de consistência para grupos de recursos. Um grupo de consistência é um contentor que pode abrigar vários volumes para que você possa gerenciá-los como uma entidade. Um grupo de consistência é snapshots simultâneos de vários volumes, fornecendo cópias consistentes de um grupo de volumes. 
---
= Como o plug-in do SnapCenter para banco de dados SAP HANA usa snapshots de grupo de consistência
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o plug-in para criar instantâneos de grupo de consistência para grupos de recursos. Um grupo de consistência é um contentor que pode abrigar vários volumes para que você possa gerenciá-los como uma entidade. Um grupo de consistência é snapshots simultâneos de vários volumes, fornecendo cópias consistentes de um grupo de volumes.

Você também pode especificar o tempo de espera para que o controlador de armazenamento agrupe snapshots de forma consistente. As opções de tempo de espera disponíveis são *urgente*, *Médio* e *descontraído*. Você também pode ativar ou desativar a sincronização WAFL (Write Anywhere File Layout) durante a operação de captura instantânea de grupo consistente. O WAFL Sync melhora o desempenho de um grupo de consistência instantâneo.
