---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: credentials 
summary: Antes de adicionar um host e instalar os pacotes de plug-in, você deve completar todos os requisitos. O plug-in do SnapCenter para banco de dados SAP HANA está disponível em ambientes Windows e Linux. 
---
= Pré-requisitos para adicionar hosts e instalar o plug-in do SnapCenter para banco de dados SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de adicionar um host e instalar os pacotes de plug-in, você deve completar todos os requisitos. O plug-in do SnapCenter para banco de dados SAP HANA está disponível em ambientes Windows e Linux.

* Você deve ter instalado o Java 11 em seu host.
+

NOTE: O IBM Java não é suportado.

* Você deve ter instalado o terminal interativo do banco de dados SAP HANA (cliente HDBSQL) no host.
* Para o Windows, o Plug-in Creator Service deve ser executado usando o usuário Windows "'LocalSystem'", que é o comportamento padrão quando o Plug-in para SAP HANA Database é instalado como administrador de domínio.
* Para o Windows, as chaves de armazenamento de usuários devem ser criadas como usuário DO SISTEMA.
* Ao instalar um plug-in em um host do Windows, se você especificar uma credencial que não está integrada ou se o usuário pertence a um usuário local do grupo de trabalho, será necessário desativar o UAC no host. O plug-in do SnapCenter para Microsoft Windows será implantado por padrão com o plug-in SAP HANA em hosts do Windows.
* Para o host Linux, as chaves HDB Secure User Store são acessadas como usuário HDBSQL os.
* O servidor SnapCenter deve ter acesso ao 8145 ou à porta personalizada do plug-in para o host de banco de dados SAP HANA.




== Hosts do Windows

* Você deve ter um usuário de domínio com Privileges de administrador local com permissões de login local no host remoto.
* Ao instalar o plug-in para banco de dados SAP HANA em um host Windows, o plug-in do SnapCenter para Microsoft Windows é instalado automaticamente.
* Você deve ter habilitado a conexão SSH baseada em senha para o usuário root ou não root.
* Você deve ter instalado o Java 11 em seu host Windows.
+
http://www.java.com/en/download/manual.jsp["Downloads Java para todos os sistemas operacionais"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"]





== Hosts Linux

* Você deve ter habilitado a conexão SSH baseada em senha para o usuário root ou não root.
* Você deve ter instalado o Java 11 em seu host Linux.
+
http://www.java.com/en/download/manual.jsp["Downloads Java para todos os sistemas operacionais"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"]

* Para bancos de dados SAP HANA que estão sendo executados em um host Linux, ao instalar o plug-in para banco de dados SAP HANA, o plug-in do SnapCenter para UNIX é instalado automaticamente.
* Você deve ter *bash* como o shell padrão para instalação do plug-in.




== Comandos suplementares

Para executar um comando complementar no plug-in do SnapCenter para SAP HANA, você deve incluí-lo no `allowed_commands.config` arquivo.

`allowed_commands.config` O arquivo está localizado no subdiretório "etc" do plug-in do SnapCenter para o diretório SAP HANA.

.Hosts do Windows
Predefinição: `C:\Program Files\NetApp\SnapCenter\HANA\etc\allowed_commands.config`

Caminho personalizado: `<Custome_Directory>\NetApp\SnapCenter\HANA\etc\allowed_commands.config` Windows host:

.Hosts Linux
Predefinição: `/opt/NetApp/snapcenter/scc/etc/allowed_commands.config`

Caminho personalizado: `<Custome_Directory>/NetApp/snapcenter/scc/etc/allowed_commands.config`

Para permitir comandos suplementares no host do plug-in, abra `allowed_commands.config` o arquivo em um editor. Insira cada comando em uma linha separada. Não é sensível a maiúsculas e minúsculas. Por exemplo,

comando: montar

comando: umount

Certifique-se de que especifica o nome de caminho totalmente qualificado. Coloque o nome do caminho entre aspas (") se ele contiver espaços. Por exemplo,

Comando: "C: Arquivos de programas/comandos NetApp/sdcli.exe"

comando: myscript.bat

Se o `allowed_commands.config` arquivo não estiver presente, os comandos ou execução de script serão bloqueados e o fluxo de trabalho falhará com o seguinte erro:

"[/mnt/mount -a] execução não permitida. Autorize adicionando o comando no arquivo %s no host do plugin."

Se o comando ou script não estiver presente no `allowed_commands.config`, a execução do comando ou script será bloqueada e o fluxo de trabalho falhará com o seguinte erro:

"[/mnt/mount -a] execução não permitida. Autorize adicionando o comando no arquivo %s no host do plugin."


NOTE: Você não deve usar uma entrada curinga (*) para permitir todos os comandos.
