---
permalink: protect-hana/reference_types_of_restore_strategies_supported_for_manually_added_sap_hana_resources.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Você deve definir uma estratégia antes de executar operações de restauração com êxito usando o SnapCenter. Existem dois tipos de estratégias de restauração para recursos do SAP HANA adicionados manualmente. Não é possível recuperar recursos do SAP HANA adicionados manualmente. 
---
= Tipos de estratégias de restauração compatíveis com recursos do SAP HANA adicionados manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve definir uma estratégia antes de executar operações de restauração com êxito usando o SnapCenter. Existem dois tipos de estratégias de restauração para recursos do SAP HANA adicionados manualmente. Não é possível recuperar recursos do SAP HANA adicionados manualmente.


NOTE: Não é possível recuperar recursos do SAP HANA adicionados manualmente.



== Restauração completa de recursos

* Restaura todos os volumes, qtrees e LUNs de um recurso



NOTE: Se o recurso contiver volumes ou qtrees, os instantâneos obtidos após o instantâneo selecionado para restauração nesses volumes ou qtrees serão excluídos e não poderão ser recuperados. Além disso, se qualquer outro recurso estiver hospedado nos mesmos volumes ou qtrees, esse recurso também será excluído.



== Restauração no nível do arquivo

* Restaura arquivos de volumes, qtrees ou diretórios
* Restaura apenas os LUNs selecionados

