---
permalink: protect-hana/task_create_backup_policies_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: Antes de usar o SnapCenter para fazer backup dos recursos do banco de dados do SAP HANA, você precisa criar uma política de backup para o recurso ou grupo de recursos que deseja fazer backup. Uma política de backup é um conjunto de regras que regem como você gerencia, agenda e retém backups. 
---
= Criar políticas de backup para bancos de dados SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o SnapCenter para fazer backup dos recursos do banco de dados do SAP HANA, você precisa criar uma política de backup para o recurso ou grupo de recursos que deseja fazer backup. Uma política de backup é um conjunto de regras que regem como você gerencia, agenda e retém backups.

.Antes de começar
* Você precisa ter definido sua estratégia de backup.
+
Para obter detalhes, consulte as informações sobre como definir uma estratégia de proteção de dados para bancos de dados SAP HANA.

* Você precisa se preparar para a proteção de dados concluindo tarefas como instalar o SnapCenter, adicionar hosts, configurar conexões do sistema de storage e adicionar recursos.
* O administrador do SnapCenter deve ter atribuído os SVMs para os volumes de origem e destino a você se estiver replicando snapshots em um espelho ou cofre.
+
Além disso, você pode especificar as configurações de replicação, script e aplicativo na política. Essas opções economizam tempo quando você deseja reutilizar a política para outro grupo de recursos.

* Reveja os pré-requisitos e limitações específicos da sincronização ativa do SnapMirror. Para obter informações, https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limites de objetos para sincronização ativa do SnapMirror"]consulte .


.Sobre esta tarefa
* Replicação do sistema SAP HANA
+
** Você pode proteger o sistema principal do SAP HANA e todas as operações de proteção de dados podem ser executadas.
** Você pode proteger o sistema SAP HANA secundário, mas os backups não podem ser criados.
+
Após o failover, toda a operação de proteção de dados pode ser executada à medida que o sistema SAP HANA secundário se torna o sistema SAP HANA primário.

+
Você não pode criar um backup para o volume de dados do SAP HANA, mas o SnapCenter continua a proteger os volumes que não são de dados (NDV).



* SnapLock
+
** Se a opção 'reter as cópias de backup para um número específico de dias' estiver selecionada, o período de retenção do SnapLock deve ser menor ou igual aos dias de retenção mencionados.
** Especificar um período de bloqueio instantâneo impede a exclusão dos instantâneos até que o período de retenção expire. Isso pode levar a reter um número maior de instantâneos do que a contagem especificada na política.
** Para a versão ONTAP 9.12,1 e inferior, os clones criados a partir dos instantâneos do Vault do SnapLock como parte da restauração herdarão o tempo de expiração do SnapLock Vault. O administrador do storage deve limpar manualmente os clones após o tempo de expiração do SnapLock.




.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *políticas*.
. Clique em *novo*.
. Na página Nome, insira o nome e os detalhes da política.
. Na página tipo de política, execute as seguintes etapas:
+
** Escolha o tipo de armazenamento
** Escolha o tipo de cópia de segurança:
+
|===
| Se você quiser... | Faça isso... 


 a| 
Crie um backup usando a tecnologia Snapshot
 a| 
Selecione *Snapshot based*.



 a| 
Efetue uma verificação de integridade da base de dados
 a| 
Selecione *Backup baseado em arquivos*. Somente os locatários ativos são copiados.

|===


. Na página Snapshot e replicação, execute as seguintes etapas:
+
** Especifique o tipo de agendamento selecionando *on demand*, *Hourly*, *Daily*, *Weekly* ou *Monthly*.
+

NOTE: Você pode especificar a programação (data de início, data de término e frequência) para a operação de backup enquanto cria um grupo de recursos. Isso permite que você crie grupos de recursos que compartilham a mesma política e frequência de backup, mas também permite que você atribua diferentes programações de backup a cada política.

+

NOTE: Se você tiver agendado para as 2:00 da manhã, o horário não será acionado durante o horário de verão (DST).



. Na página Snapshot e replicação, especifique as configurações de retenção para o tipo de backup e o tipo de agendamento selecionado na página tipo de backup:
+
|===
| Se você quiser... | Então... 


 a| 
Mantenha um certo número de instantâneos
 a| 
Selecione *Copies to keep* e especifique o número de instantâneos que deseja manter.

Se o número de Snapshots exceder o número especificado, os Snapshots mais antigos serão excluídos primeiro.


NOTE: O valor máximo de retenção é 1018.  Os backups falharão se a retenção for definida como um valor maior do que o suportado pela versão do ONTAP .


IMPORTANT: Para backups baseados em cópias Snapshot, defina a contagem de retenção para 2 ou superior, se quiser habilitar a replicação do SnapVault. Se você definir a contagem de retenção como 1, a operação de retenção poderá falhar porque o primeiro snapshot é o snapshot de referência para a relação SnapVault até que um snapshot mais recente seja replicado para o destino.


NOTE: Para replicação do sistema SAP HANA, recomenda-se adicionar todos os recursos do sistema SAP HANA a um grupo de recursos. Isso garante que o número certo de backups seja retido.


NOTE: Para a replicação do sistema SAP HANA, o total de snapshots obtidos será igual ao conjunto de retenção para o grupo de recursos. A remoção do Snapshot mais antigo é baseada em qual nó o Snapshot mais antigo está localizado. Por exemplo, a retenção está definida como 7 para um grupo de recursos com SAP HANA System Replication primário e SAP HANA System Replication secundário. Você pode tirar um máximo de 7 snapshots de cada vez, incluindo SAP HANA System Replication Primary e SAP HANA System Replication secundário.



 a| 
Mantenha as capturas instantâneas por um determinado número de dias
 a| 
Selecione *reter cópias para* e especifique o número de dias para os quais deseja manter as capturas instantâneas antes de excluí-las.



 a| 
Período de bloqueio de cópia de instantâneo
 a| 
Selecione *Período de bloqueio de cópia de instantâneo* e especifique dias, meses ou anos.

O período de retenção do SnapLock deve ser inferior a 100 anos.

|===
. Selecione uma etiqueta Snapshot.
+

NOTE: Você pode atribuir rótulos SnapMirror a snapshots primários para replicação remota, permitindo que os snapshots primários descarreguem a operação de replicação de snapshots do SnapCenter para sistemas secundários ONTAP .  Isso pode ser feito sem habilitar a opção SnapMirror ou SnapVault na página de política.

. Para backups baseados em cópia Snapshot, na seção Selecionar opções de replicação secundária, selecione uma ou ambas as opções de replicação secundária a seguir:
+
|===
| Para este campo... | Faça isso... 


 a| 
*Atualizar SnapMirror depois de criar uma cópia Snapshot local*
 a| 
Selecione este campo para criar cópias espelhadas dos conjuntos de backup em outro volume (replicação SnapMirror).

Esta opção deve estar ativada para a sincronização ativa do SnapMirror.

Se a relação de proteção no ONTAP for do tipo espelho e Cofre e se você selecionar somente essa opção, a captura Instantânea criada no primário não será transferida para o destino, mas será listada no destino. Se esta captura Instantânea for selecionada no destino para executar uma operação de restauração, a localização secundária não estará disponível para a mensagem de erro de backup abobadado/espelhado selecionada será exibida.

Durante a replicação secundária, o tempo de expiração do SnapLock carrega o tempo de expiração do SnapLock primário.

Clicar no botão *Atualizar* na página topologia atualiza o tempo de expiração do SnapLock secundário e primário que são recuperados do ONTAP.

link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Veja os backups e clones do banco de dados SAP HANA na página topologia"]Consulte .



 a| 
*Atualizar SnapVault depois de criar uma cópia Snapshot local*
 a| 
Selecione esta opção para executar a replicação de backup disco a disco (backups SnapVault).

Durante a replicação secundária, o tempo de expiração do SnapLock carrega o tempo de expiração do SnapLock primário. Clicar no botão *Atualizar* na página topologia atualiza o tempo de expiração do SnapLock secundário e primário que são recuperados do ONTAP.

Quando o SnapLock é configurado apenas no secundário do ONTAP conhecido como SnapLock Vault, clicar no botão *Atualizar* na página topologia atualiza o período de bloqueio no secundário que é recuperado do ONTAP.

Para obter mais informações sobre o SnapLock Vault, consulte https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Armazene cópias Snapshot em WORM em um destino de cofre"]

link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Veja os backups e clones do banco de dados SAP HANA na página topologia"]Consulte .



 a| 
*Contagem de tentativas de erro*
 a| 
Introduza o número máximo de tentativas de replicação que podem ser permitidas antes de a operação parar.

|===
+

NOTE: Você deve configurar a política de retenção do SnapMirror no ONTAP para o storage secundário para evitar atingir o limite máximo de snapshots no storage secundário.

. Revise o resumo e clique em *Finish*.

