---
permalink: protect-scc/backup_schedules_of_custom_plug_in_resources.html 
sidebar: sidebar 
keywords: custom plug-in 
summary: O fator mais crítico na determinação de um agendamento de backup é a taxa de alteração do recurso. Quanto mais você fizer backup de seus recursos, menos Registros de arquivamento que o SnapCenter precisa usar para restaurar, o que pode resultar em operações de restauração mais rápidas. 
---
= Agendamentos de backup de recursos personalizados de plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O fator mais crítico na determinação de um agendamento de backup é a taxa de alteração do recurso. Quanto mais você fizer backup de seus recursos, menos Registros de arquivamento que o SnapCenter precisa usar para restaurar, o que pode resultar em operações de restauração mais rápidas.

Você pode fazer backup de um recurso muito usado a cada hora, enquanto você pode fazer backup de um recurso raramente usado uma vez por dia. Outros fatores incluem a importância do recurso para a sua organização, seu contrato de nível de serviço (SLA) e seu objetivo do ponto de restauração (RPO).

O SLA define o nível de serviço esperado e aborda muitos problemas relacionados ao serviço, incluindo a disponibilidade e o desempenho do serviço. O RPO define a estratégia para a era dos arquivos que precisam ser recuperados do armazenamento de backup para que as operações regulares sejam retomadas após uma falha. O SLA e o RPO contribuem para a estratégia de proteção de dados.

Os programas de backup têm duas partes, como segue:

* Frequência de backup
+
A frequência de backup (com que frequência os backups devem ser executados), também chamada de tipo de agendamento para alguns plug-ins, faz parte de uma configuração de política. Por exemplo, você pode configurar a frequência de backup como hora, dia, semanal ou mensal. Você pode acessar políticas na GUI do SnapCenter clicando em *Configurações* > *políticas*.

* Fazer backup de programações
+
As programações de backup (exatamente quando os backups devem ser executados) fazem parte de uma configuração de recurso ou grupo de recursos. Por exemplo, se você tiver um grupo de recursos que tenha uma política configurada para backups semanais, poderá configurar a programação para fazer backup todas as quintas-feiras às 10:00 horas. Você poderá acessar programações de grupos de recursos na GUI do SnapCenter clicando em *Resources*, selecionando o plug-in apropriado e clicando em *Exibir* > *Grupo de recursos*.


