---
permalink: protect-scc/create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: credentials 
summary: Você deve criar uma conexão de sistema de armazenamento e uma credencial antes de usar cmdlets do PowerShell para executar operações de proteção de dados. 
---
= Crie uma conexão de sistema de armazenamento e uma credencial usando cmdlets do PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar uma conexão de máquina virtual de armazenamento (SVM) e uma credencial antes de usar cmdlets do PowerShell para executar operações de proteção de dados.

.Antes de começar
* Você deve ter preparado o ambiente do PowerShell para executar os cmdlets do PowerShell.
* Você deve ter as permissões necessárias na função Administrador da infraestrutura para criar conexões de armazenamento.
* Você deve garantir que as instalações do plug-in não estão em andamento.
+
As instalações de plug-in do host não devem estar em andamento ao adicionar uma conexão de sistema de armazenamento, pois o cache do host pode não ser atualizado e o status dos bancos de dados pode ser exibido na GUI do SnapCenter como "'não disponível para backup'" ou "'não no armazenamento NetApp'".

* Os nomes do sistema de armazenamento devem ser exclusivos.
+
O SnapCenter não é compatível com vários sistemas de storage com o mesmo nome em clusters diferentes. Cada sistema de storage com suporte do SnapCenter deve ter um nome exclusivo e um endereço IP de LIF de gerenciamento exclusivo.



.Passos
. Inicie uma sessão de conexão do PowerShell Core usando o cmdlet Open-SmConnection.
+
Este exemplo abre uma sessão do PowerShell:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Crie uma nova conexão com o sistema de armazenamento usando o cmdlet Add-SmStorageConnection.
+
Este exemplo cria uma nova conexão de sistema de armazenamento:

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Crie uma nova credencial usando o cmdlet Add-SmCredential.
+
Este exemplo cria uma nova credencial chamada FinanceAdmin com credenciais do Windows:

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _get-Help command_name_. Em alternativa, pode também consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência de cmdlet do software SnapCenter"^].
