---
permalink: protect-scc/snapcenter_custom_plug_ins_overview.html 
sidebar: sidebar 
keywords: custom plug-ins 
summary: Você pode desenvolver plug-ins personalizados para aplicações que usa e usar o SnapCenter para fazer backup, restauração ou clone dessas aplicações. Como outros plug-ins do SnapCenter, seus plug-ins personalizados atuam como componentes do lado do host do software NetApp SnapCenter, permitindo a proteção de dados com reconhecimento de aplicações e o gerenciamento de recursos. 
---
= Visão geral dos plug-ins personalizados do SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desenvolver plug-ins personalizados para aplicações que usa e usar o SnapCenter para fazer backup, restauração ou clone dessas aplicações. Seus plug-ins personalizados funcionam como componentes do lado do host do software NetApp SnapCenter, permitindo a proteção de dados com reconhecimento de aplicações e o gerenciamento de recursos.

Quando plug-ins personalizados são instalados, você pode usar a tecnologia SnapCenter com NetApp SnapMirror para criar cópias espelhadas de conjuntos de backup em outro volume e usar a tecnologia NetApp SnapVault para executar a replicação de backup disco para disco. Os plug-ins personalizados podem ser usados em ambientes Windows e Linux.


NOTE: SnapCenterCLI não suporta comandos de plug-ins personalizados.

Você pode instalar o plug-in personalizado na página Adicionar host.

link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["Adicione hosts e instale pacotes plug-in em hosts remotos."^]


NOTE: A política de suporte do SnapCenter cobrirá o suporte para a estrutura de plug-in personalizada do SnapCenter, mecanismo central e as APIs associadas. O suporte não cobrirá o código-fonte do plug-in e os scripts associados criados na estrutura de plug-in personalizada.

Você pode criar seus próprios plug-ins personalizados consultando link:develop_a_plug_in_for_your_application.html["Desenvolva um plug-in para sua aplicação"^]o guia.
