= 
:allow-uri-read: 


.Passos
. Inicie uma sessão de conexão com o servidor SnapCenter para um usuário especificado usando o cmdlet Open-SmConnection.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146
----
+
É apresentado o aviso de nome de utilizador e palavra-passe.

. Crie uma política de backup usando o cmdlet Add-SmPolicy.
+
Este exemplo cria uma nova política de backup com um tipo de backup SQL de fullbackup:

+
[listing]
----
PS C:\> Add-SmPolicy -PolicyName TESTPolicy
-PluginPolicyType SCSQL -PolicyType Backup
-SqlBackupType FullBackup -Verbose
----
+
Este exemplo cria uma nova política de backup com um tipo de backup do sistema de arquivos do Windows CrashConsistent:

+
[listing]
----
PS C:\> Add-SmPolicy -PolicyName FileSystemBackupPolicy
-PluginPolicyType SCW -PolicyType Backup
-ScwBackupType CrashConsistent -Verbose
----
. Descubra os recursos do host usando o cmdlet Get-SmResources.
+
Este exemplo descobre os recursos do plug-in Microsoft SQL no host especificado:

+
[listing]
----
C:\PS>PS C:\> Get-SmResources -HostName vise-f6.sddev.mycompany.com
-PluginCode SCSQL
----
+
Este exemplo descobre os recursos para sistemas de arquivos do Windows no host especificado:

+
[listing]
----
C:\PS>PS C:\> Get-SmResources -HostName vise2-f6.sddev.mycompany.com
-PluginCode SCW
----
. Adicione um novo grupo de recursos ao SnapCenter usando o cmdlet Add-SmResourceGroup.
+
Este exemplo cria um novo grupo de recursos de backup de banco de dados SQL com a política e os recursos especificados:

+
[listing]
----
PS C:\> Add-SmResourceGroup -ResourceGroupName AccountingResource
-Resources @{"Host"="visef6.org.com";
"Type"="SQL Database";"Names"="vise-f6\PayrollDatabase"}
-Policies "BackupPolicy"
----
+
Este exemplo cria um novo grupo de recursos de backup do sistema de arquivos do Windows com a política e os recursos especificados:

+
[listing]
----
PS C:\> Add-SmResourceGroup -ResourceGroupName EngineeringResource
-PluginCode SCW -Resources @{"Host"="WIN-VOK20IKID5I";
"Type"="Windows Filesystem";"Names"="E:\"}
-Policies "EngineeringBackupPolicy"
----
. Inicie uma nova tarefa de backup usando o cmdlet New-SmBackup.
+
[listing]
----
PS C:> New-SmBackup -ResourceGroupName PayrollDataset -Policy FinancePolicy
----
. Exiba o status da tarefa de backup usando o cmdlet Get-SmBackupReport.
+
Este exemplo exibe um relatório de resumo de todos os trabalhos executados na data especificada:

+
[listing]
----
PS C:\> Get-SmJobSummaryReport -Date '1/27/2016'
----


As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _get-Help command_name_. Em alternativa, pode também consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência de cmdlet do software SnapCenter"^].
