---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Crie a credencial do Azure no SnapCenter para acessar a conta do Azure NetApp. 
---
= Crie a credencial do Azure no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar a credencial do Azure no SnapCenter para acessar a conta do Azure NetApp.

.Antes de começar
* Certifique-se de ter criado o princípio de serviço no Azure.
* Certifique-se de que você tem o ID do locatário, o ID do cliente e a chave secreta associados ao responsável de serviço disponível com você.
+
** O ID do Locatário pode ser encontrado no Portal do Azure na página Visão geral do ID do Entra.
** O ID do cliente também é conhecido como ID do aplicativo para o Enterprise App/Service Principal. Isso pode ser encontrado no Portal do Azure na página Visão geral do aplicativo corporativo que você criou para atuar como o principal de serviço do SnapCenter.
** A chave secreta do cliente também é conhecida como o valor secreto. Você pode criar esse segredo de cliente no Portal do Azure navegando até *inscrições de aplicativos* em Entra ID. Depois de selecionar a aplicação Enterprise que criou, navegue até *certificados e segredos* e, em seguida, *segredo de novo cliente*.
+

NOTE: O valor secreto só pode ser acessado quando criado. Você não pode acessá-lo mais tarde.

** O responsável de Serviço precisa receber permissões. A função de Colaborador permitirá que o responsável do serviço execute as ações necessárias no Azure. Isso pode ser concedido a partir da página Controle de Acesso (IAM) na página assinatura.




.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credential*.
. Clique em *novo*.
. Na página Credential (credencial), especifique as seguintes informações necessárias para criar a credencial.
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Introduza um nome para a credencial.



 a| 
Modo de autenticação
 a| 
Selecione *credencial do Azure* na lista suspensa.



 a| 
ID do inquilino
 a| 
Insira o ID do locatário.



 a| 
ID do cliente
 a| 
Introduza a ID do cliente.



 a| 
Chave secreta do cliente
 a| 
Introduza a chave secreta do cliente.

|===
. Clique em *OK*.

