---
permalink: protect-azure/create-backup-policies-sap-hana.html 
sidebar: sidebar 
keywords: create policies, SAP HANA, backup policies 
summary: Crie uma política de backup para o grupo de recursos ou recursos que você deseja fazer backup. 
---
= Criar políticas de backup para bancos de dados SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o SnapCenter para fazer backup dos recursos do banco de dados do SAP HANA, você precisa criar uma política de backup para o recurso ou grupo de recursos que deseja fazer backup.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *políticas*.
. Clique em *novo*.
. Na página Nome, insira o nome e a descrição da política.
. Na página tipo de política, execute as seguintes etapas:
+
.. Selecione *Azure NetApp Files* como o tipo de armazenamento.
.. Selecione *File-based* (baseado em ficheiros) se pretender efetuar uma verificação de integridade da base de dados.
.. Selecione *Snapshot based* se quiser criar um backup usando a tecnologia Snapshot.


. Na página Snapshot e backup, execute as seguintes etapas:
+
.. Selecione a frequência da cópia de segurança agendada.
.. Especifique as definições de retenção.
.. Se você quiser habilitar o backup do Azure NetApp Files, selecione *Ativar backup* e especifique as configurações de retenção.


. Revise o resumo e clique em *Finish*.

