---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: Crie a credencial para adicionar o host do plug-in. 
---
= Crie a credencial para adicionar o host do plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter.

Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credential*.
. Clique em *novo*.
. Na página Credential (credencial), especifique as seguintes informações necessárias para criar a credencial.
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Introduza um nome para a credencial.



 a| 
Modo de autenticação
 a| 
Selecione o modo de autenticação na lista pendente.



 a| 
Tipo de autenticação
 a| 
Selecione *baseado em senha* ou *baseado em chave SSH* (somente para host Linux).



 a| 
Nome de utilizador
 a| 
Especifique o nome de usuário.



 a| 
Palavra-passe
 a| 
Se tiver selecionado a autenticação baseada na palavra-passe, especifique a palavra-passe.



 a| 
Chave privada SSH
 a| 
Se você selecionou a autenticação baseada em chave SSH, especifique a chave privada.



 a| 
Use sudo Privileges
 a| 
Marque a caixa de seleção usar sudo Privileges se estiver criando credenciais para um usuário que não seja root.


NOTE: Isso é aplicável apenas para usuários Linux.

|===
. Clique em *OK*.

