---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Crie a credencial do Azure no SnapCenter para acessar a conta do Azure NetApp. 
---
= Crie a credencial do Azure no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar a credencial do Azure no SnapCenter para acessar a conta do Azure NetApp.

Antes de criar a credencial do Azure, certifique-se de que criou o principal de serviço no Azure. O ID do locatário, o ID do cliente e a chave secreta associados ao responsável do serviço serão necessários para criar a credencial do Azure.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credential*.
. Clique em *novo*.
. Na página Credential (credencial), especifique as seguintes informações necessárias para criar a credencial.
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Introduza um nome para a credencial.



 a| 
Modo de autenticação
 a| 
Selecione *credencial do Azure* na lista suspensa.



 a| 
ID do inquilino
 a| 
Insira o ID do locatário.



 a| 
ID do cliente
 a| 
Introduza a ID do cliente.



 a| 
Chave secreta do cliente
 a| 
Introduza a chave secreta do cliente.

|===
. Clique em *OK*.

