---
permalink: protect-azure/protect-applications-azure-netapp-files.html 
sidebar: sidebar 
keywords: azure netapp files, ANF, back up, restore, clone, ANF backup, Azure Blob storage 
summary: É possível fazer backup, restaurar e clonar aplicações em execução no Azure NetApp Files. 
---
= Proteja aplicativos em execução no Azure NetApp Files
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter é compatível com a proteção de aplicações como Oracle, SQL e SAP HANA que residem no Azure NetApp Files. A partir da versão 6.0.1, o SnapCenter dá suporte ao recurso de backup Azure NetApp Files que expande os recursos de proteção de dados do Azure NetApp Files fornecendo solução de backup totalmente gerenciada para recuperação, arquivamento e conformidade de longo prazo.

O Azure NetApp Files é uma solução de storage premium que pode ser cara para a retenção de backup a longo prazo. Para otimizar custos, você pode migrar os backups do storage Azure NetApp Files para um armazenamento de objetos Azure. A partir do SnapCenter 6,0.1, é possível fazer backup e clonar aplicativos que residem no Azure NetApp Files para o armazenamento de Blobs do Azure (armazenamento de objetos). Você pode manter duas cópias dos seus dados, cópias snapshot de volume no storage Azure NetApp Files para recuperação de curto prazo e outra cópia no armazenamento Blob do Azure para recuperação de longo prazo.

Quando uma política com backup do Azure NetApp Files está habilitada e associada a um recurso, o SnapCenter manipula a criação de snapshots de volume e o backup no armazenamento de Blobs do Azure. O SnapCenter cria o cofre de backup e habilita o backup para o volume. Se você ativou o backup para o volume, o SnapCenter utiliza o cofre existente.



== Limitações

* As funcionalidades de armazenamento de objetos para sistemas de armazenamento FAS, ASA ou AFF ONTAP e Amazon FSX for NetApp ONTAP não são suportadas.
* Os workflows de montagem e catálogo do Oracle e SAP HANA não são compatíveis com backups de storage de objetos, mas são compatíveis com snapshots.
* Os clones do Oracle PDB não são compatíveis com backups de storage de objetos, mas são compatíveis com snapshots.
* A verificação de backup do storage de objetos, suporte à API REST, gerenciamento do ciclo de vida de clones do storage de objetos e recursos de geração de relatórios para backups de storage de objetos não é compatível.
* A restauração de backups no armazenamento de Blobs do Azure para o Azure NetApp Files não é suportada. Você pode usar a opção clone, alternativamente.
* Divisão de clones não é suportada.

