---
permalink: admin/task_manage_rbac.html 
sidebar: sidebar 
keywords: modify RBAC, role, users, groups 
summary: O SnapCenter permite modificar funções, usuários e grupos. 
---
= Gerenciar RBAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter permite modificar funções, usuários e grupos.



== Modificar uma função

É possível modificar uma função SnapCenter para remover usuários ou grupos e alterar as permissões associadas à função. É especialmente útil modificar funções quando você deseja alterar ou eliminar as permissões usadas por uma função inteira.

.Antes de começar
Você deve ter feito login como a função "SnapCenterAdmin".


NOTE: Não é possível modificar ou remover permissões para a função SnapCenterAdmin.

*Passos*

. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *funções*.
. No campo Nome da função, clique na função que deseja modificar.
. Selecione *todos os membros desta função podem ver objetos de outros membros* para permitir que outros membros da função vejam recursos como volumes e hosts depois que eles atualizarem a lista de recursos.
+
Desmarque essa opção se você não quiser que os membros dessa função vejam objetos aos quais outros membros são atribuídos.

+

NOTE: Quando essa opção está ativada, a atribuição de acesso aos usuários a objetos ou recursos não é necessária se os usuários pertencerem à mesma função que o usuário que criou os objetos ou recursos.

. Na página Detalhes da função altere as permissões ou desmarque os membros conforme necessário.
. Clique em *Enviar*.




== Modificar usuários e grupos

Você pode modificar usuários ou grupos do SnapCenter para alterar suas funções e ativos.

.Antes de começar
Você deve estar logado como administrador do SnapCenter.

*Passos*

. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *usuários e Acesso*.
. Na lista Nome do usuário ou grupo, clique no usuário ou grupo que você deseja modificar.
. Na página Detalhes do Usuário ou Grupo, altere funções e ativos.
. Clique em *Enviar*.

