---
permalink: admin/task_request_status_reports_of_the_jobs_from_the_dashboard.html 
sidebar: sidebar 
keywords: dashboard, snapcenter 
summary: Você pode solicitar relatórios sobre tarefas de backup, restauração e clone na página Painel de controle. Isso é útil se você quiser identificar o número total de trabalhos bem-sucedidos ou com falha em seu ambiente SnapCenter. 
---
= Solicitar relatórios de status dos trabalhos a partir do painel de controle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode solicitar relatórios sobre tarefas de backup, restauração e clone na página Painel de controle. Isso é útil se você quiser identificar o número total de trabalhos bem-sucedidos ou com falha em seu ambiente SnapCenter.

*Passos*

. No painel de navegação esquerdo, clique em *Dashboard*
. Localize o bloco de tarefas no Painel de instrumentos e selecione *Backup*, *Restore* ou *Clone*.
. Utilizando o menu pendente, selecione o período de tempo para o qual pretende obter informações sobre trabalhos: 24 horas, 7 dias ou 30 dias.
+
Os sistemas exibem um gráfico de rosca cobrindo os dados.

. Clique no corte de rosca que representa as informações do trabalho para o qual deseja um relatório.
+
Quando você clica no gráfico de rosca, você é redirecionado da página Painel para a página Monitor. A página Monitor exibe os trabalhos com o status selecionado no gráfico de rosca.

. Na lista de páginas Monitor, clique em um trabalho específico para selecioná-lo.
. Na parte superior da página Monitor, clique em *relatórios*.


*Resultado*

O relatório apresenta informações apenas para o trabalho selecionado. Pode rever o relatório ou transferi-lo para o seu sistema local.
