---
permalink: protect-postgresql/host-requirements-to-install-snapcenter-plug-in-package-for-windows-postgresql.html 
sidebar: sidebar 
keywords: postgresql 
summary: Antes de instalar o pacote de plug-ins do SnapCenter para Windows, você deve estar familiarizado com alguns requisitos básicos de espaço do sistema host e requisitos de dimensionamento. 
---
= Requisitos de host para instalar o pacote de plug-ins do SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o pacote de plug-ins do SnapCenter para Windows, você deve estar familiarizado com alguns requisitos básicos de espaço do sistema host e requisitos de dimensionamento.

|===
| Item | Requisitos 


 a| 
Sistemas operacionais
 a| 
Microsoft Windows

Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].



 a| 
RAM mínima para o plug-in SnapCenter no host
 a| 
1 GB



 a| 
Espaço mínimo de instalação e log para o plug-in SnapCenter no host
 a| 
5 GB


NOTE: Deve alocar espaço em disco suficiente e monitorizar o consumo de armazenamento pela pasta de registos. O espaço de registo necessário varia consoante o número de entidades a proteger e a frequência das operações de proteçãoão de dados. Se não houver espaço em disco suficiente, os logs não serão criados para as operações executadas recentemente.



 a| 
Pacotes de software necessários
 a| 
* DOTNET Core começando com a versão 8.0.5 e incluindo todos os patches .NET 8 subsequentes
* PowerShell Core 7.4.2


Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].

Para obter informações específicas de solução de problemas .NET, consulte https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["A atualização ou instalação do SnapCenter falha para sistemas legados que não têm conetividade com a Internet."]

|===