---
permalink: protect-postgresql/types-of-restore-strategies-supported-for-manually-added-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Você deve definir uma estratégia antes de executar operações de restauração com êxito usando o SnapCenter. Existem dois tipos de estratégias de restauração para recursos PostgreSQL adicionados manualmente. Você não pode recuperar recursos PostgreSQL adicionados manualmente. 
---
= Tipos de estratégias de restauração suportadas para recursos PostgreSQL adicionados manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve definir uma estratégia antes de executar operações de restauração com êxito usando o SnapCenter.


NOTE: Você não pode recuperar recursos PostgreSQL adicionados manualmente.



== Restauração completa de recursos

* Restaura todos os volumes, qtrees e LUNs de um recurso



NOTE: Se o recurso contiver volumes ou qtrees, os instantâneos obtidos após o snapshot selecionado para restauração em tais volumes ou qtrees serão excluídos e não poderão ser recuperados. Além disso, se qualquer outro recurso estiver hospedado nos mesmos volumes ou qtrees, esse recurso também será excluído.

OBSERVAÇÃO: O plug-in para PostgreSQL cria uma pasta backup_label e tablespace_map na pasta _/<OS_temp_folder>/postgresql_SC_recovery_<Restore_JobId>/_ para ajudar a recuperar manualmente .
