---
permalink: protect-postgresql/types-of-restore-performed-for-auto-discovered-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for postgresql 
summary: 'O SnapCenter oferece suporte a SnapRestore (VBSR) baseado em volume, SnapRestore de arquivo único e tipos de restauração de conexão e cópia para clusters PostgreSQL descobertos automaticamente.' 
---
= Tipos de operações de restauração para PostgreSQL descoberto automaticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O plug-in do SnapCenter para PostgreSQL é compatível com SnapRestore de arquivo único e tipos de restauração de conexão e cópia para clusters PostgreSQL descobertos automaticamente.



== O SnapRestore de arquivo único é executado em ambientes NFS para os seguintes cenários:

* Se apenas a opção *Complete Resource* estiver selecionada
* Quando o backup selecionado é de um local secundário SnapMirror ou SnapVault e a opção *recurso completo* está selecionada




== O SnapRestore de Arquivo único é executado em ambientes SAN para os seguintes cenários:

* Se apenas a opção *Complete Resource* estiver selecionada
* Quando o backup é selecionado em um local secundário do SnapMirror ou do SnapVault e a opção *recurso completo* está selecionada

