---
permalink: install/concept_svm_connections_and_credentials.html 
sidebar: sidebar 
keywords: storage, connection, credentials 
summary: Antes de executar operações de proteção de dados, você deve configurar as conexões de armazenamento e adicionar as credenciais que o servidor SnapCenter e os plug-ins SnapCenter usarão. 
---
= Conexões e credenciais de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de executar operações de proteção de dados, você deve configurar as conexões de armazenamento e adicionar as credenciais que o servidor SnapCenter e os plug-ins SnapCenter usarão.

* * Conexões de armazenamento*
+
As conexões de armazenamento dão aos plug-ins do servidor SnapCenter e do SnapCenter acesso ao armazenamento do ONTAP. A configuração dessas conexões também envolve a configuração de recursos do AutoSupport e do sistema de Gerenciamento de Eventos (EMS).

* *Credenciais*
+
** Administrador de domínio ou qualquer membro do grupo de administradores
+
Especifique o administrador do domínio ou qualquer membro do grupo de administradores no sistema no qual você está instalando o plug-in do SnapCenter. Formatos válidos para o campo Nome de usuário são:

+
*** _NetBIOS_username_
*** _Domain FQDN_username_
*** _upn_


** Administrador local (apenas para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local incorporado no sistema no qual você está instalando o plug-in SnapCenter. Você pode especificar uma conta de usuário local que pertence ao grupo de administradores locais se a conta de usuário tiver Privileges elevado ou o recurso de controle de acesso do usuário estiver desativado no sistema host.

+
O formato válido para o campo Nome de usuário é: _Nome de usuário_

** Credenciais para grupos de recursos individuais
+
Se você configurar credenciais para grupos de recursos individuais e o nome de usuário não tiver Privileges de administrador completo, será necessário atribuir pelo menos o grupo de recursos e Privileges de backup ao nome de usuário.




