---
permalink: install/learn-about-supporting-asa-r2-in-snapcenter.html 
sidebar: sidebar 
keywords: ASA r2 systems 
summary: O SnapCenter 6,1 dá suporte a sistemas ASA R2 que criam uma experiência simplificada específica para as necessidades de clientes somente SAN. 
---
= Saiba mais sobre o suporte aos sistemas ASA R2 no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter 6,1 dá suporte a sistemas ASA R2 que criam uma experiência simplificada específica para as necessidades de clientes somente SAN.

Os sistemas ASA R2 dão suporte a todos os protocolos SAN (iSCSI, FC e NVMe em TCP/IP) em uma única implantação de par de HA. Os protocolos SCSI (iSCSI e FC) usam uma arquitetura ativo-ativo simétrica para multipathing de modo que todos os caminhos entre os hosts e o storage estejam ativos/otimizados. Os protocolos iSCSI e NVMe/TCP dão suporte a caminhos diretos entre os hosts e o storage.


NOTE: O SnapCenter suporta apenas o sistema de arquivos de máquina virtual (VMFS) VMware em sistemas ASA R2.

Os sistemas ASA R2 introduzem o uso de unidades de storage com grupos de consistência:

* Uma unidade de armazenamento disponibiliza espaço de armazenamento aos seus hosts SAN para operações de dados. Uma unidade de storage refere-se a um LUN para hosts SCSI ou a um namespace NVMe para hosts NVMe.
* Um grupo de consistência é uma coleção de unidades de armazenamento que são gerenciadas como uma única unidade.


Os sistemas ASA R2 usam unidades de storage e grupos de consistência para simplificar o gerenciamento de storage e a proteção de dados. Por exemplo, suponha que você tenha um banco de dados composto por 10 unidades de armazenamento em um grupo de consistência, e você precisa fazer backup de todo o banco de dados. Em vez de fazer backup de cada unidade de armazenamento individualmente, você pode proteger todo o banco de dados fazendo backup do grupo de consistência.

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Saiba mais sobre os sistemas ASA R2"].



== O que é suportado no SnapCenter 6,1 para sistemas ASA R2

O SnapCenter permite que você execute as seguintes operações em todos os aplicativos compatíveis com o SnapCenter se você estiver usando sistemas de storage ASA R2:

* Criação de backups primários de aplicativos através do VMDK
* Transferir instantâneos de grupo de consistência para o sistema de armazenamento secundário
* Restaurar os backups e restaurar a partir de um local alternativo
+
** Restauração no local a partir de storage primário e secundário com o VMware vMotion
** Conecte e copie a restauração a partir de storage primário e secundário


* Clonagem dos backups e clonagem para um local alternativo




== O que não é suportado no SnapCenter 6,1 para sistemas ASA R2

* Mapeamento de dispositivo bruto (RDM)
* Volumes de aplicações para Oracle
* SAP HANA NDV
* LockVault
* Snapshot à prova de violações
* Grupo flexível
* Grupo de consistência hierárquica
* Migração do ONTAP 9.x para sistemas ASA R2
* Renomeação de snapshots
* O provisionamento secundário do diretório de log do host plug-in SQL não é suportado pelo SnapCenter. Você deve configurar manualmente usando a CLI do ONTAP ou o Gerenciador do sistema.

