---
permalink: install/reference_features_enabled_on_your_windows_host_during_installation.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: O instalador do servidor SnapCenter permite os recursos e funções do Windows em seu host Windows durante a instalação. Isso pode ser de interesse para fins de solução de problemas e manutenção do sistema host. 
---
= Recursos ativados em seu host Windows durante a instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O instalador do servidor SnapCenter permite os recursos e funções do Windows em seu host Windows durante a instalação. Isso pode ser de interesse para fins de solução de problemas e manutenção do sistema host.

|===
| Categoria | Recurso 


 a| 
Servidor Web
 a| 
* Serviços de informações da Internet
* Serviços Web mundiais
* Recursos HTTP comuns
+
** Documento padrão
** Navegação de diretório
** Erros HTTP
** Redirecionamento HTTP
** Conteúdo estático
** Publicação WebDAV


* Saúde e Diagnóstico
+
** Registo personalizado
** Registo HTTP
** Ferramentas de registo
** Monitorização de pedidos
** Traçado


* Recursos de desempenho
+
** Compressão de conteúdo estático


* Segurança
+
** Segurança IP
** Autenticação básica
** Suporte centralizado a certificados SSL
** Autenticação Mapeamento certificado Cliente
** Autenticação de mapeamento de certificados do cliente IIS
** Restrições de IP e domínio
** Filtragem de solicitação
** Autorização de URL
** Autenticação do Windows


* Recursos de desenvolvimento de aplicativos
+
** Extensão .NET 4,5
** Inicialização da aplicação
** Pacote de Hospedagem ASP.NET Core começando com a versão 8.0.5 e incluindo todos os patches .NET 8 subsequentes
** O lado do servidor inclui
** Protocolo WebSocket


* Ferramentas de gerenciamento
+
** Console de gerenciamento do IIS






 a| 
Scripts e ferramentas de gerenciamento do IIS
 a| 
* Serviço de Gestão do IIS
* Ferramentas de gerenciamento da Web




 a| 
O NET Framework 8.0.5 é um dos nossos selecionados Jogos de Plataforma
 a| 
* .NET Framework começando com a versão 8.0.5 e incluindo todos os patches .NET 8 subsequentes
* ASP.NET começando com a versão 8.0.5 e incluindo todos os patches .NET 8 subsequentes
* Windows Communication Foundation (WCF) HTTP Activation45
+
** Ativação TCP
** Ativação HTTP




Para obter informações específicas de solução de problemas .NET, https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["A atualização ou instalação do SnapCenter falha para sistemas legados que não têm conetividade com a Internet"^] consulte .



 a| 
Fila de mensagens
 a| 
* Serviços de enfileiramento de mensagens
+

NOTE: Certifique-se de que nenhum outro aplicativo use o serviço MSMQ que o SnapCenter cria e gerencia.

* RabbitMQ




 a| 
Serviço de ativação do processo do Windows
 a| 
* Modelo do processo




 a| 
APIs de configuração
 a| 
Tudo

|===