---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: Você deve garantir que os requisitos de conexões e portas sejam atendidos antes de instalar os plug-ins do servidor SnapCenter e do aplicativo ou do banco de dados. 
---
= Requisitos de conexão e porta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve garantir que os requisitos de conexões e portas sejam atendidos antes de instalar os plug-ins do servidor SnapCenter e do aplicativo ou do banco de dados.

* Os aplicativos não podem compartilhar uma porta.
+
Cada porta deve ser dedicada ao aplicativo apropriado.

* Para portas personalizáveis, você pode selecionar uma porta personalizada durante a instalação se não quiser usar a porta padrão.
+
Você pode alterar uma porta de plug-in após a instalação usando o assistente Modificar host.

* Para portas fixas, você deve aceitar o número de porta padrão.
* Firewalls
+
** Firewalls, proxies ou outros dispositivos de rede não devem interferir nas conexões.
** Se você especificar uma porta personalizada ao instalar o SnapCenter, adicione uma regra de firewall no host do plug-in para essa porta para o Loader de plug-ins do SnapCenter.




A tabela a seguir lista as diferentes portas e seus valores padrão.

|===
| Nome da porta | Números das portas | Protocolo | Direção | Descrição 


 a| 
Porta SnapCenter
 a| 
8146
 a| 
HTTPS
 a| 
Bidirecional
 a| 
Esta porta é usada para comunicação entre o cliente SnapCenter (o usuário SnapCenter) e o servidor SnapCenter e também é usada para comunicação dos hosts plug-in para o servidor SnapCenter.

Você pode personalizar o número da porta.



 a| 
Porta de comunicação SnapCenter SMCore
 a| 
8145
 a| 
HTTPS
 a| 
Bidirecional
 a| 
Esta porta é usada para comunicação entre o servidor SnapCenter e os hosts onde os plug-ins do SnapCenter estão instalados.

Você pode personalizar o número da porta.



 a| 
Porta de serviço do Agendador
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
Esta porta é usada para orquestrar os fluxos de trabalho do agendador do SnapCenter para todos os plug-ins gerenciados dentro do host do servidor SnapCenter de maneira centralizada.

Você pode personalizar o número da porta.



 a| 
Porto RabbitMQ
 a| 
5672
 a| 
TCP
 a| 
 a| 
Esta é a porta padrão em que o RabbitMQ escuta e é usada para comunicação entre o serviço de Agendador e o SnapCenter.



 a| 
Porta MySQL
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
A porta é usada para se comunicar com o banco de dados do repositório do SnapCenter. Você pode criar conexões seguras do servidor SnapCenter para o servidor MySQL. link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["Saiba mais"]



 a| 
Hosts de plug-in do Windows
 a| 
135, 445
 a| 
TCP
 a| 
 a| 
Esta porta é usada para comunicação entre o servidor SnapCenter e o host no qual o plug-in está sendo instalado. O intervalo de portas dinâmico adicional especificado pela Microsoft também deve estar aberto.



 a| 
Hosts plug-in Linux ou AIX
 a| 
22
 a| 
SSH
 a| 
Unidirecional
 a| 
Esta porta é usada para comunicação entre o servidor SnapCenter e o host, iniciada do servidor para o host cliente.



 a| 
Pacote de plug-ins do SnapCenter para Windows, Linux ou AIX
 a| 
8145
 a| 
HTTPS
 a| 
Bidirecional
 a| 
Esta porta é usada para comunicação entre SMCore e hosts onde o pacote plug-ins está instalado. Personalizável.

Você pode personalizar o número da porta.



 a| 
Plug-in SnapCenter para banco de dados Oracle
 a| 
27216
 a| 
 a| 
 a| 
A porta JDBC padrão é usada pelo plug-in para Oracle para conexão com o banco de dados Oracle.



 a| 
Plug-in do SnapCenter para banco de dados do Exchange
 a| 
909
 a| 
 a| 
 a| 
A porta NET.TCP padrão é usada pelo plug-in para Windows para conetar-se aos retornos de chamada do Exchange VSS.



 a| 
Plug-ins compatíveis com NetApp para SnapCenter
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
Esta é uma porta interna que é usada somente no host de plug-in personalizado; nenhuma exceção de firewall é necessária.

A comunicação entre o servidor SnapCenter e plug-ins personalizados é roteada através da porta 8145.



 a| 
Porta de comunicação do cluster ONTAP ou SVM
 a| 
* 443 (HTTPS)
* 80 (HTTP)

 a| 
* HTTPS
* HTTP

 a| 
Bidirecional
 a| 
A porta é usada pela sal (camada de abstração de storage) para comunicação entre o host que executa o servidor SnapCenter e o SVM. Atualmente, a porta também é usada pelo sal em hosts plug-in do SnapCenter para Windows para comunicação entre o host do plug-in do SnapCenter e o SVM.



 a| 
Plug-in do SnapCenter para banco de dados SAP HANA
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
Bidirecional
 a| 
Para um locatário único de contentor de banco de dados multitenant (MDC), o número da porta termina com 13; para não MDC, o número da porta termina com 15.

Você pode personalizar o número da porta.



 a| 
Plug-in SnapCenter para PostgreSQL
 a| 
5432
 a| 
 a| 
 a| 
Esta porta é a porta PostgreSQL padrão usada para comunicação pelo plug-in para PostgreSQL para o cluster PostgreSQL.

Você pode personalizar o número da porta.

|===
Para modificar os detalhes da porta, link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["Modificar hosts de plug-in"]consulte .
