---
permalink: install/task_configure_root_or_intermediate_certificates_to_trust_store.html 
sidebar: sidebar 
keywords: enable certificate-based authentication,configure CA signed key pair,configure root, configure intermediate certificates 
summary: Você deve configurar os certificados raiz ou intermediários para o SPL Trust-store. 
---
= Configure certificados raiz ou intermediários para o armazenamento de confiança SPL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar os certificados raiz ou intermediários para o SPL Trust-store. Você deve adicionar o certificado de CA raiz e, em seguida, os certificados de CA intermediários.

*Passos*

. Navegue até a pasta que contém o keystore SPL: `/var/opt/snapcenter/spl/etc`.
. Localize o arquivo `keystore.jks`.
. Liste os certificados adicionados no keystore:
`$ keytool -list -v -keystore keystore.jks`
. Adicione um certificado raiz ou intermediário:
`$ keytool -import -trustcacerts -alias <AliasNameForCerticateToBeImported> -file /<CertificatePath> -keystore` `keystore.jks`
. Reinicie o serviço depois de configurar os certificados raiz ou intermédios para o armazenamento de confiança SPL.




== Configure o par de chaves assinadas da CA para o armazenamento de confiança SPL

Você deve configurar o par de chaves assinadas da CA para o armazenamento de confiança SPL.

*Passos*

. Navegue até a pasta que contém o keystore do SPL `/var/opt/snapcenter/spl/etc` .
. Localize o arquivo `keystore.jks``.
. Liste os certificados adicionados no keystore:
`$ keytool -list -v -keystore keystore.jks`
. Adicione o certificado da CA com chave privada e pública.
`$ keytool -importkeystore -srckeystore <CertificatePathToImport> -srcstoretype pkcs12 -destkeystore keystore.jks` `-deststoretype JKS`
. Liste os certificados adicionados no keystore.
`$ keytool -list -v -keystore keystore.jks`
. Verifique se o keystore contém o alias correspondente ao novo certificado da CA, que foi adicionado ao keystore.
. Altere a senha da chave privada adicionada para o certificado da CA para a senha do keystore.
+
A senha padrão do keystore SPL é o valor da chave SPL_KEYSTORE_PASS no `spl.properties` arquivo.

+
`$ keytool -keypasswd -alias "<aliasNameOfAddedCertInKeystore>" -keystore keystore.jks``

. Se o nome do alias no certificado da CA for longo e contiver espaço ou carateres especiais ("*",","), altere o nome do alias para um nome simples:
`$ keytool -changealias -alias "<OrignalAliasName>" -destalias "<NewAliasName>" -keystore keystore.jks``
. Configure o nome do alias a partir do keystore localizado no `spl.properties` arquivo. Atualize este valor com a chave SPL_CERTIFICATE_ALIAS.
. Reinicie o serviço depois de configurar o par de chaves assinadas pela CA para o armazenamento de confiança SPL.

