---
permalink: install/task_switch_from_nlb_to_f5_for_high_availability.html 
sidebar: sidebar 
keywords: F5, NLB, high availability 
summary: 'Você pode alterar sua configuração do SnapCenter HA de balanceamento de carga de rede (NLB) para usar o balanceador de carga F5.' 
---
= Mude de NLB para F5 para obter alta disponibilidade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar sua configuração do SnapCenter HA de balanceamento de carga de rede (NLB) para usar o balanceador de carga F5.

*Passos*

. Configurar servidores SnapCenter para alta disponibilidade usando o F5. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_SnapCenter_Servers_for_high_availability_using_F5_Load_Balancer["Saiba mais"^].
. No host do servidor SnapCenter, inicie o PowerShell.
. Inicie uma sessão usando o cmdlet Open-SmConnection e insira suas credenciais.
. Atualize o servidor SnapCenter para apontar para o endereço IP do cluster F5 usando o cmdlet Update-SmServerCluster.
+
As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _get-Help command_name_. Em alternativa, pode também consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência de cmdlet do software SnapCenter"^].


