---
permalink: install/task_log_in_to_snapcenter.html 
sidebar: sidebar 
keywords: log in, logging, SnapCenter UI, modify timeout, GUI session timeout, disbale SSL 3.0, SSL 3.0, security 
summary: 'O SnapCenter é compatível com controles de acesso baseados em função (RBAC). O administrador do SnapCenter atribui funções e recursos por meio do SnapCenter RBAC a um usuário no grupo de trabalho ou diretório ativo ou a grupos no diretório ativo. O usuário RBAC agora pode fazer login no SnapCenter com as funções atribuídas.' 
---
= Faça login no SnapCenter usando a autorização RBAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter é compatível com controles de acesso baseados em função (RBAC). O administrador do SnapCenter atribui funções e recursos por meio do SnapCenter RBAC a um usuário no grupo de trabalho ou diretório ativo ou a grupos no diretório ativo. O usuário RBAC agora pode fazer login no SnapCenter com as funções atribuídas.

.Antes de começar
* Você deve ativar o Serviço de ativação do processo do Windows (WAS) no Gerenciador do Windows Server.
* Se pretender utilizar o Internet Explorer como browser para iniciar sessão no servidor SnapCenter, deve certificar-se de que o modo protegido no Internet Explorer está desativado.
* Se o servidor SnapCenter estiver instalado no host Linux, você deve fazer login usando a conta de usuário que foi usada para instalar o servidor SnapCenter.


*Sobre esta tarefa*

Durante a instalação, o assistente de instalação do servidor SnapCenter cria um atalho e o coloca na área de trabalho e no menu Iniciar do host onde o SnapCenter está instalado. Além disso, no final da instalação, o assistente de instalação exibe o URL do SnapCenter com base nas informações fornecidas durante a instalação, que você pode copiar se quiser fazer login de um sistema remoto.


IMPORTANT: Se você tiver várias guias abertas no navegador da Web, fechar apenas a guia do navegador do SnapCenter não fará o logout do SnapCenter. Para terminar sua conexão com o SnapCenter, você deve sair do SnapCenter clicando no botão *Sair* ou fechando todo o navegador da Web.

|===


| *Prática recomendada:* por motivos de segurança, recomenda-se que não ative o seu navegador para guardar a sua palavra-passe do SnapCenter. 
|===
O URL padrão da GUI é uma conexão segura com a porta padrão 8146 no servidor onde o servidor SnapCenter está instalado (_\https://server:8146_). Se você forneceu uma porta de servidor diferente durante a instalação do SnapCenter, essa porta será usada.

Para a implantação de alta disponibilidade (HA), você deve acessar o SnapCenter usando o IP _\https://Virtual_Cluster_IP_or_FQDN:8146_. do cluster virtual Se você não vir a IU do SnapCenter ao navegar para _\https://Virtual_Cluster_IP_or_FQDN:8146_ no Internet Explorer (IE), você deve adicionar o endereço IP do cluster virtual ou FQDN como um site confiável no IE em cada host de plug-in ou desativar a Segurança aprimorada do IE em cada host de plug-in. Para obter mais informações, https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Unable_to_access_cluster_IP_address_from_outside_network["Não é possível acessar o endereço IP do cluster a partir da rede externa"^]consulte .

Além de usar a GUI do SnapCenter, você pode usar cmdlets do PowerShell para criar scripts para executar operações de configuração, backup e restauração. Alguns cmdlets podem ter sido alterados com cada versão do SnapCenter. O https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência de cmdlet do software SnapCenter"^] tem os detalhes.


NOTE: Se estiver a iniciar sessão no SnapCenter pela primeira vez, tem de iniciar sessão utilizando as credenciais fornecidas durante o processo de instalação.

*Passos*

. Inicie o SnapCenter a partir do atalho localizado na área de trabalho do host local, ou a partir do URL fornecido no final da instalação, ou a partir do URL fornecido pelo administrador do SnapCenter.
. Introduza as credenciais do utilizador.
+
|===
| Para especificar o seguinte... | Use um destes formatos... 


 a| 
Administrador de domínio
 a| 
** NetBIOS/nome de usuário
** Sufixo UPN
+
Por exemplo, NetApp.com

** Nome de usuário do domínio




 a| 
Administrador local
 a| 
Nome de utilizador

|===
. Se lhe for atribuída mais de uma função, na caixa função, selecione a função que pretende utilizar para esta sessão de início de sessão.
+
Seu usuário atual e sua função associada são mostrados no canto superior direito do SnapCenter depois que você estiver conetado.



*Resultado*

É apresentada a página Painel de instrumentos.

Se o log falhar com o erro de que o site não pode ser alcançado, você deve mapear o certificado SSL para o SnapCenter. https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Protection_and_Security%2FSnapCenter%2FSnapCenter_will_not_open_with_error_%2522This_site_can%2527t_be_reached%2522["Saiba mais"^]

*Depois de terminar*

Depois de efetuar login no servidor SnapCenter como usuário RBAC pela primeira vez, atualize a lista de recursos.

Se você tiver domínios não confiáveis do ative Directory que deseja que o SnapCenter ofereça suporte, Registre esses domínios no SnapCenter antes de configurar as funções dos usuários em domínios não confiáveis. link:../install/task_register_untrusted_active_directory_domains.html["Saiba mais"^].

Se você quiser adicionar o host do plug-in no SnapCenter em execução no host Linux, você deve obter o arquivo de checksum do local: _/opt/NetApp/SnapCenter/SnapManagerWeb/Repository_.

A partir da versão 6,0, um atalho para o SnapCenter PowerShell é criado na área de trabalho. Você pode acessar diretamente os cmdlets do SnapCenter PowerShell usando o atalho.



== Faça login no SnapCenter usando autenticação multifator (MFA)

O servidor SnapCenter suporta MFA para conta de domínio, que faz parte do diretório ativo.

.Antes de começar
Você deve ter habilitado o MFA. Para obter informações sobre como ativar o MFA, consulte link:../install/enable_multifactor_authentication.html["Ativar a autenticação multifator"]

*Sobre esta tarefa*

* Apenas o FQDN é suportado
* Os usuários de grupos de trabalho e entre domínios não podem fazer login usando MFA


*Passos*

. Inicie o SnapCenter a partir do atalho localizado na área de trabalho do host local, ou a partir do URL fornecido no final da instalação, ou a partir do URL fornecido pelo administrador do SnapCenter.
. Na página de login do AD FS, insira Nome de usuário e Senha.
+
Quando a mensagem de erro inválida de nome de usuário ou senha for exibida na página do AD FS, você deve verificar o seguinte:

+
** Se o nome de usuário ou senha é válido
+
A conta de usuário deve existir no ative Directory (AD)

** Se você excedeu o máximo de tentativas permitidas que foi definido no AD
** Se o AD e o AD FS estão ativos e em execução






== Modifique o tempo limite padrão da sessão da GUI do SnapCenter

Você pode modificar o período de tempo limite da sessão da GUI do SnapCenter para torná-lo menor ou maior que o período de tempo limite padrão de 20 minutos.

Como um recurso de segurança, após um período padrão de 15 minutos de inatividade, o SnapCenter avisa que você será desconetado da sessão da GUI em 5 minutos. Por padrão, o SnapCenter faz o logout da sessão da GUI após 20 minutos de inatividade e você deve fazer login novamente.

*Passos*

. No painel de navegação esquerdo, clique em *Settings* > *Global Settings*.
. Na página Configurações globais, clique em *Configurações de configuração*.
. No campo tempo limite da sessão, insira o tempo limite da nova sessão em minutos e clique em *Salvar*.




== Proteja o servidor web SnapCenter desativando o SSL 3,0

Para fins de segurança, você deve desativar o protocolo SSL (Secure Socket Layer) 3,0 no Microsoft IIS se ele estiver ativado no servidor da Web SnapCenter.

Há falhas no protocolo SSL 3,0 que um invasor pode usar para causar falhas de conexão, ou para executar ataques man-in-the-middle e observar o tráfego de criptografia entre seu site e seus visitantes.

*Passos*

. Para iniciar o Editor de Registro no host do servidor web do SnapCenter, clique em *Iniciar* > *Executar* e, em seguida, digite regedit.
. No Editor de Registro, navegue até HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 3,0.
+
** Se a chave do servidor já existir:
+
... Selecione o DWORD ativado e clique em *Editar* > *Modificar*.
... Altere o valor para 0 e clique em *OK*.


** Se a chave do servidor não existir:
+
... Clique em *Editar* > *novo* > *chave* e, em seguida, nomeie o servidor de chaves.
... Com a nova chave de servidor selecionada, clique em *Edit* > *New* > *DWORD*.
... Nomeie o novo DWORD habilitado e insira 0 como o valor.




. Feche o Editor de Registro.

