---
permalink: install/task_install_the_snapcenter_server_using_the_install_wizard.html 
sidebar: sidebar 
keywords: install, snapcenter software, install wizard, features enabled 
summary: Você pode executar o executável do instalador do servidor SnapCenter para instalar o servidor SnapCenter. 
---
= Instale o servidor SnapCenter no host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o executável do instalador do servidor SnapCenter para instalar o servidor SnapCenter.

Opcionalmente, você pode executar vários procedimentos de instalação e configuração usando cmdlets do PowerShell. Você deve estar usando o PowerShell 7.4.2 ou posterior.


NOTE: A instalação silenciosa do servidor SnapCenter a partir da linha de comando não é suportada.

.Antes de começar
* O host do servidor SnapCenter deve estar atualizado com as atualizações do Windows sem reiniciar o sistema pendente.
* Você deve ter assegurado que o servidor MySQL não está instalado no host onde você pretende instalar o servidor SnapCenter.
* Você deve ter habilitado a depuração do instalador do Windows.
+
Consulte o site da Microsoft para obter informações sobre como ativar https://support.microsoft.com/kb/223300["Registo do instalador do Windows"^]o .

+

NOTE: Você não deve instalar o servidor SnapCenter em um host que tenha servidores Microsoft Exchange, ative Directory ou nomes de domínio.



.Passos
. Baixe o pacote de instalação do servidor SnapCenter em https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["Site de suporte da NetApp"^].
. Inicie a instalação do servidor SnapCenter clicando duas vezes no arquivo .exe baixado.
+
Depois de iniciar a instalação, todas as pré-verificações são executadas e, se os requisitos mínimos não forem atendidos, as mensagens de erro ou aviso apropriadas serão exibidas.

+
Você pode ignorar as mensagens de aviso e prosseguir com a instalação; no entanto, os erros devem ser corrigidos.

. Reveja os valores pré-preenchidos necessários para a instalação do servidor SnapCenter e modifique, se necessário.
+
Você não precisa especificar a senha para o banco de dados do repositório do MySQL Server. Durante a instalação do servidor SnapCenter, a senha é gerada automaticamente.

+

NOTE: O caráter especial "'%`" is not supported in the custom path for the repository database. If you include "`%" no caminho, falha na instalação.

. Clique em *Instalar agora*.
+
Se você tiver especificado quaisquer valores inválidos, as mensagens de erro apropriadas serão exibidas. Você deve reinserir os valores e, em seguida, iniciar a instalação.

+

NOTE: Se você clicar no botão *Cancelar*, a etapa que está sendo executada será concluída e, em seguida, iniciar a operação de reversão. O servidor SnapCenter será completamente removido do host.

+
No entanto, se você clicar em *Cancelar* quando as operações "SnapCenter Server site Restart" ou "Waiting for SnapCenter Server to start" estiverem sendo executadas, a instalação continuará sem cancelar a operação.

+
Os ficheiros de registo estão sempre listados (o mais antigo primeiro) na pasta %temp% do utilizador admin. Se você quiser redirecionar os locais de log, inicie a instalação do servidor SnapCenter a partir do prompt de comando executando:``C:\installer_location\installer_name.exe /log"C:\"``





== Recursos habilitados no host Windows durante a instalação

O instalador do servidor SnapCenter permite os recursos e funções do Windows em seu host Windows durante a instalação. Elas podem ser interessantes para solução de problemas e manutenção do sistema host.

|===
| Categoria | Recurso 


 a| 
Servidor Web
 a| 
* Serviços de informações da Internet
* Serviços Web mundiais
* Recursos HTTP comuns
+
** Documento padrão
** Navegação de diretório
** Erros HTTP
** Redirecionamento HTTP
** Conteúdo estático
** Publicação WebDAV


* Saúde e Diagnóstico
+
** Registo personalizado
** Registo HTTP
** Ferramentas de registo
** Monitorização de pedidos
** Traçado


* Recursos de desempenho
+
** Compressão de conteúdo estático


* Segurança
+
** Segurança IP
** Autenticação básica
** Suporte centralizado a certificados SSL
** Autenticação Mapeamento certificado Cliente
** Autenticação de mapeamento de certificados do cliente IIS
** Restrições de IP e domínio
** Filtragem de solicitação
** Autorização de URL
** Autenticação do Windows


* Recursos de desenvolvimento de aplicativos
+
** Extensão .NET 4,5
** Inicialização da aplicação
** Pacote de Hospedagem ASP.NET Core Runtime 8.0.12 (e todos os patches 8,0.x subsequentes)
** O lado do servidor inclui
** Protocolo WebSocket


* Ferramentas de gerenciamento
+
** Console de gerenciamento do IIS






 a| 
Scripts e ferramentas de gerenciamento do IIS
 a| 
* Serviço de Gestão do IIS
* Ferramentas de gerenciamento da Web




 a| 
O NET Framework 8.0.12 é um dos nossos selecionados Jogos de Plataforma
 a| 
* Pacote de Hospedagem ASP.NET Core Runtime 8.0.12 (e todos os patches 8,0.x subsequentes)
* Windows Communication Foundation (WCF) HTTP Activation45
+
** Ativação TCP
** Ativação HTTP




Para obter informações específicas de solução de problemas .NET, https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["A atualização ou instalação do SnapCenter falha para sistemas legados que não têm conetividade com a Internet"^] consulte .



 a| 
Serviço de ativação do processo do Windows
 a| 
Modelo do processo



 a| 
APIs de configuração
 a| 
Tudo

|===