---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: Você deve configurar o certificado CA com o site SnapCenter no host Windows. 
---
= Configure o certificado CA com o site SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o certificado CA com o site SnapCenter no host Windows.

*Passos*

. Abra o Gerenciador do IIS no servidor Windows em que o SnapCenter está instalado.
. No painel de navegação esquerdo, clique em *Connections* (ligações).
. Expanda o nome do servidor e *sites*.
. Selecione o site do SnapCenter no qual você deseja instalar o certificado SSL.
. Navegue até *ações* > *Editar Site*, clique em *ligações*.
. Na página ligações, selecione *encadernação para https*.
. Clique em *Editar*.
. Na lista suspensa certificado SSL, selecione o certificado SSL recentemente importado.
. Clique em *OK*.
+

NOTE: O site do Agendador de SnapCenter (porta padrão: 8154, HTTPS) é configurado com certificado autoassinado. Esta porta está se comunicando dentro do host do servidor SnapCenter e não é obrigatório configurar com um certificado de CA. No entanto, se o seu ambiente exigir que você use um certificado de CA, repita as etapas de 5 a 9 usando o site Agendador de SnapCenter.




NOTE: Se o certificado da CA recentemente implantado não estiver listado no menu suspenso, verifique se o certificado da CA está associado à chave privada.


IMPORTANT: Certifique-se de que o certificado é adicionado usando o seguinte caminho: *Raiz da consola > certificados – computador local > autoridades de certificação raiz fidedignas > certificados*.
