---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user 
summary: Antes de adicionar um host e instalar os pacotes de plug-ins, você deve completar todos os requisitos. 
---
= Pré-requisitos para adicionar hosts e instalar o pacote Plug-ins para Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de adicionar um host e instalar o pacote de plug-ins para Linux, você deve completar todos os requisitos.

* Se estiver a utilizar iSCSI, o serviço iSCSI tem de estar em execução.
* Você pode usar a autenticação baseada em senha para o usuário root ou não root ou autenticação baseada em chave SSH.
+

NOTE: A chave RSA é o único formato de chave SSH compatível para SnapCenter. Consulte o artigo da Knowledge Base link:https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/How_to_create_an_RSA_key_for_SnapCenter_SSH_Key_Based_credential["Como criar uma chave RSA para SnapCenter credencial baseada em chave SSH"^] para obter detalhes sobre como criar a chave SSH.

+
O plug-in do SnapCenter para sistemas de arquivos Unix pode ser instalado por um usuário não-root. No entanto, você deve configurar o sudo Privileges para que o usuário não-root instale e inicie o processo de plug-in. Depois de instalar o plug-in, os processos serão executados como um usuário não-root eficaz.

* Crie credenciais com o modo de autenticação como Linux para o usuário de instalação.
* Você precisa ter instalado o Java 17 para SnapCenter 6.2.1 ou posterior ou
* Java 11 para SnapCenter 6.2 e anteriores no seu host Linux.
+

NOTE: Certifique-se de ter instalado apenas a edição certificada do Java 17 para SnapCenter 6.2.1 e posteriores ou do Java 11 para SnapCenter 6.2 e anteriores no host Linux.

+
Para obter informações sobre downloads do Java, consulte link:https://www.oracle.com/java/technologies/downloads/#java17["Baixe o Java para todos os sistemas operacionais"^].

* Você deve ter *bash* como o shell padrão para instalação do plug-in.




== Requisitos de Host Linux

Você deve garantir que o host atenda aos requisitos antes de instalar o pacote de plug-ins do SnapCenter para Linux.

|===
| Item | Requisitos 


 a| 
Sistemas operacionais
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)




 a| 
RAM mínima para o plug-in SnapCenter no host
 a| 
2 GB



 a| 
Espaço mínimo de instalação e log para o plug-in SnapCenter no host
 a| 
2 GB


NOTE: Deve alocar espaço em disco suficiente e monitorizar o consumo de armazenamento pela pasta de registos. O espaço de registo necessário varia consoante o número de entidades a proteger e a frequência das operações de proteçãoão de dados. Se não houver espaço em disco suficiente, os logs não serão criados para as operações executadas recentemente.



 a| 
Pacotes de software necessários
 a| 
* Java 17 (Oracle Java ou OpenJDK) para SnapCenter 6.2.1 e posterior ou
* Java 11 para SnapCenter 6.2 e versões anteriores



NOTE: Certifique-se de ter instalado apenas a edição certificada do Java 17 para SnapCenter 6.2.1 e posteriores ou do Java 11 para SnapCenter 6.2 e anteriores no host Linux.

Se você atualizou o Java para a versão mais recente, certifique-se de que a opção JAVA_HOME localizada em /var/opt/snapcenter/spl/etc/spl.properties esteja definida com a versão correta do Java e o caminho correto.

|===
Para obter as informações mais recentes sobre as versões compatíveis, consulte o https://imt.netapp.com/imt/imt.jsp?components=180320;180338;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].
