---
permalink: protect-scu/task_determine_whether_unix_file_systems_are_available_for_backup.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for UNIX file systems, discovery,file systems, UNIX, Unix file systems 
summary: Depois de instalar o plug-in para sistemas de arquivos Unix, os sistemas de arquivos no host são automaticamente descobertos e exibidos na página recursos. 
---
= Descubra os sistemas de arquivos UNIX disponíveis para backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de instalar o plug-in, todos os sistemas de arquivos nesse host são automaticamente descobertos e exibidos na página recursos. Você pode adicionar esses sistemas de arquivos a grupos de recursos para executar operações de proteção de dados.

.Antes de começar
* Você deve ter concluído tarefas como instalar o servidor SnapCenter, adicionar hosts e criar conexões do sistema de armazenamento.
* Se os sistemas de arquivos residirem em um disco de máquina virtual (VMDK) ou mapeamento de dispositivo bruto (RDM), você deverá implantar o plug-in do SnapCenter para VMware vSphere e Registrar o plug-in com o SnapCenter.
+
Para obter mais informações, https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html["Implante o plug-in do SnapCenter para VMware vSphere"^]consulte .



.Passos
. No painel de navegação esquerdo, clique em *Resources* e selecione o plug-in apropriado na lista.
. Na página recursos, selecione *caminho* na lista Exibir.
. Clique em *Atualizar recursos*.
+
Os sistemas de arquivos são exibidos juntamente com informações como tipo, nome do host, grupos e políticas de recursos associados e status.


