---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: Antes de usar o SnapCenter para fazer backup dos recursos do banco de dados IBM DB2, você deve criar uma política de backup para o grupo de recursos ou recursos que deseja fazer backup. Uma política de backup é um conjunto de regras que regem como você gerencia, agenda e retém backups. 
---
= Criar políticas de backup para o IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o SnapCenter para fazer backup de recursos do IBM DB2, você deve criar uma política de backup para o grupo de recursos ou recursos que deseja fazer backup. Uma política de backup é um conjunto de regras que regem como você gerencia, agenda e retém backups.

.Antes de começar
* Você precisa ter definido sua estratégia de backup.
+
Para obter detalhes, consulte as informações sobre como definir uma estratégia de proteção de dados para bancos de dados IBM DB2.

* Você precisa se preparar para a proteção de dados concluindo tarefas como instalar o SnapCenter, adicionar hosts, configurar conexões do sistema de storage e adicionar recursos.
* O administrador do SnapCenter deve ter atribuído os SVMs para os volumes de origem e destino a você se estiver replicando snapshots em um espelho ou cofre.
+
Além disso, você pode especificar as configurações de replicação, script e aplicativo na política. Essas opções economizam tempo quando você deseja reutilizar a política para outro grupo de recursos.



.Sobre esta tarefa
* SnapLock
+
** Se a opção 'reter as cópias de backup para um número específico de dias' estiver selecionada, o período de retenção do SnapLock deve ser menor ou igual aos dias de retenção mencionados.
** Especificar um período de bloqueio de instantâneos impede a exclusão dos instantâneos até que o período de retenção expire. Isso pode levar a reter um número maior de instantâneos do que a contagem especificada na política.
** Para a versão ONTAP 9.12,1 e inferior, os clones criados a partir dos snapshots do SnapLock Vault como parte da restauração herdarão o tempo de expiração do SnapLock Vault. O administrador do storage deve limpar manualmente os clones após o tempo de expiração do SnapLock.




.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *políticas*.
. Clique em *novo*.
. Na página Nome, insira o nome e os detalhes da política.
. Na página tipo de política, execute o seguinte:
+
.. Selecione o tipo de armazenamento.
.. Na seção *Configurações personalizadas de backup*, forneça quaisquer configurações específicas de backup que tenham que ser passadas para o formato de valor de chave do plug-in.
+
Você pode fornecer vários valores-chave a serem passados para o plug-in.



. Na página Snapshot e replicação, execute as seguintes ações.
+
.. Especifique a frequência da programação selecionando *on demand*, *Hourly*, *Daily*, *Weekly* ou *Monthly*.
+

NOTE: Você pode especificar a programação (data de início, data de término e frequência) para a operação de backup enquanto cria um grupo de recursos. Isso permite que você crie grupos de recursos que compartilham a mesma política e frequência de backup, mas também permite que você atribua diferentes programações de backup a cada política.

+

NOTE: Se você tiver agendado para as 2:00 da manhã, o horário não será acionado durante o horário de verão (DST).

.. Na seção Configurações de instantâneos, execute as seguintes ações:
+
|===
| Se você quiser... | Então... 


 a| 
Mantenha um certo número de instantâneos
 a| 
Selecione *Copies to keep* e especifique o número de instantâneos que deseja manter.

Se o número de instantâneos exceder o número especificado, os instantâneos serão excluídos com as cópias mais antigas excluídas primeiro.



 a| 
Mantenha as capturas instantâneas por um determinado número de dias
 a| 
Selecione *reter cópias para* e especifique o número de dias para os quais deseja manter as capturas instantâneas antes de excluí-las.



 a| 
Período de bloqueio de cópia de instantâneo
 a| 
Selecione *Período de bloqueio de cópia de instantâneo* e especifique dias, meses ou anos.

O período de retenção do SnapLock deve ser inferior a 100 anos.

|===
+

IMPORTANT: Para backups baseados em cópias Snapshot, defina a contagem de retenção para 2 ou superior, se quiser habilitar a replicação do SnapVault. Se você definir a contagem de retenção como 1, a operação de retenção pode falhar porque o primeiro snapshot é o snapshot de referência para a relação SnapVault até que um snapshot mais recente seja replicado para o destino.

.. Especifique o rótulo da política.
+
Você pode atribuir rótulos SnapMirror a snapshots primários para replicação remota, permitindo que os snapshots primários descarreguem a operação de replicação de snapshots do SnapCenter para sistemas secundários ONTAP .  Isso pode ser feito sem habilitar a opção SnapMirror ou SnapVault na página de política.



. Na seção Selecionar opções de replicação secundária, selecione uma ou ambas as seguintes opções de replicação secundária:
+
|===
| Para este campo... | Faça isso... 


 a| 
Atualize o SnapMirror depois de criar uma cópia Snapshot local
 a| 
Selecione este campo para criar cópias espelhadas dos conjuntos de backup em outro volume (replicação SnapMirror).

Esta opção deve estar ativada para a sincronização ativa do SnapMirror.



 a| 
Atualize o SnapVault depois de criar uma cópia Snapshot local
 a| 
Selecione esta opção para executar a replicação de backup disco a disco (backups SnapVault).



 a| 
Contagem de tentativas de erro
 a| 
Introduza o número máximo de tentativas de replicação que podem ser permitidas antes de a operação parar.

|===
+

NOTE: Você deve configurar a política de retenção do SnapMirror no ONTAP para o storage secundário para evitar atingir o limite máximo de snapshots no storage secundário.

. Revise o resumo e clique em *Finish*.

