---
permalink: protect-db2/snapcenter-plug-in-for-ibm-db2-features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: O SnapCenter se integra à aplicação plug-in e às tecnologias NetApp no sistema de storage. Para trabalhar com o plug-in para o banco de dados IBM DB2, use a interface gráfica do usuário do SnapCenter. 
---
= Plug-in do SnapCenter para recursos do IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter se integra à aplicação plug-in e às tecnologias NetApp no sistema de storage. Para trabalhar com o plug-in para o banco de dados IBM DB2, use a interface gráfica do usuário do SnapCenter.

* * Interface gráfica unificada do usuário*
+
A interface do SnapCenter fornece padronização e consistência em plug-ins e ambientes. A interface do SnapCenter permite concluir operações consistentes de backup, restauração e clone em plug-ins, usar relatórios centralizados, usar visualizações de painel rápidas, configurar controle de acesso baseado em funções (RBAC) e monitorar tarefas em todos os plug-ins.

* * Administração central automatizada*
+
Você pode agendar operações de backup, configurar a retenção de backup baseada em política e executar operações de restauração. Você também pode monitorar proativamente seu ambiente configurando o SnapCenter para enviar alertas por e-mail.

* *Tecnologia de cópia Snapshot NetApp sem interrupções*
+
O SnapCenter usa a tecnologia de snapshot do NetApp com o Plug-in para Banco de dados IBM DB2 para fazer backup de recursos.



O uso do Plug-in para IBM DB2 também oferece os seguintes benefícios:

* Suporte a fluxos de trabalho de backup, restauração e clone
* Delegação de funções centralizada e segurança compatível com RBAC
+
Você também pode definir as credenciais para que os usuários autorizados do SnapCenter tenham permissões no nível do aplicativo.

* Criação de cópias de recursos com uso eficiente de espaço e pontuais para teste ou extração de dados usando a tecnologia NetApp FlexClone
+
É necessária uma licença FlexClone no sistema de storage onde você deseja criar o clone.

* Suporte para o recurso instantâneo do grupo de consistência (CG) do ONTAP como parte da criação de backups.
* Funcionalidade de executar vários backups simultaneamente em vários hosts de recursos
+
Em uma única operação, os snapshots são consolidados quando os recursos em um único host compartilham o mesmo volume.

* Capacidade de criar instantâneos usando comandos externos.
* Suporte para Linux LVM no sistema de arquivos XFS.

