---
permalink: protect-nsp/configure_CA_certificate_on_windows_host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Configure o certificado CA para o serviço de plug-ins compatíveis com o NetApp no host Windows 
---
= Configure o certificado CA para o serviço de plug-ins compatíveis com o NetApp no host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve gerenciar a senha do armazenamento de chaves de plug-ins personalizados e seu certificado, configurar o certificado de CA, configurar certificados raiz ou intermediários para o armazenamento de confiança de plug-ins personalizados e configurar o par de chaves assinadas de CA para armazenamento de confiança de plug-ins personalizados personalizados com o serviço de plug-ins personalizados SnapCenter para ativar o certificado digital instalado.

Plug-ins personalizados usam o arquivo _keystore.jks_, que está localizado em _C: Arquivos de programas, NetApp, SnapCenter, SnapCenter Plug-in Creator, tanto como seu armazenamento de confiança e armazenamento de chaves.



== Gerenciar senha para armazenamento de chaves plug-in personalizado e alias do par de chaves assinadas CA em uso

.Passos
. Você pode recuperar a senha padrão do keystore do plug-in personalizado do arquivo de propriedade do agente do plug-in personalizado.
+
É o valor correspondente à chave _KEYSTORE_PASS_.

. Altere a senha do keystore:
+
_keytool -storepasswd -keystore keystore.jks_

+

NOTE: Se o comando "keytool" não for reconhecido no prompt de comando do Windows, substitua o comando keytool por seu caminho completo.

+
_C: Arquivos de programas/<jdk_version>/keytool.exe" -storepasswd -keystore keystore.jks_

. Altere a senha para todos os aliases de entradas de chave privada no keystore para a mesma senha usada para o keystore:
+
_keytool -keypasswd -alias "alias_name_in_cert" -keystore keystore.jks_

+
Atualize o mesmo para a chave KEYSTORE_PASS no arquivo _agent.properties_.

. Reinicie o serviço depois de alterar a senha.
+

NOTE: A palavra-passe para o armazenamento de chaves plug-in personalizado e para todas as palavras-passe de alias associadas da chave privada deve ser a mesma.





== Configure certificados raiz ou intermediários para armazenamento de confiança de plug-in personalizado

Você deve configurar os certificados raiz ou intermediários sem a chave privada para armazenamento de confiança de plug-in personalizado.

.Passos
. Navegue até a pasta que contém o armazenamento de chaves de plug-in personalizado _C: Arquivos de programas/NetApp/SnapCenter/SnapCenter Plug-in Creator/etc_
. Localize o arquivo 'keystore.jks'.
. Liste os certificados adicionados no keystore:
+
_keytool -list -v -keystore keystore.jks_

. Adicione um certificado raiz ou intermediário:
+
_Keytool -import -trustcacerts -alias myRootCA -file /root/USERTrustRSA_root.cer -keystore keystore.jks_

. Reinicie o serviço depois de configurar os certificados raiz ou intermédios para o armazenamento de confiança de plug-in personalizado.



NOTE: Você deve adicionar o certificado de CA raiz e, em seguida, os certificados de CA intermediários.



== Configure o par de chaves assinadas da CA para o armazenamento de confiança de plug-in personalizado

Você deve configurar o par de chaves assinadas da CA para o armazenamento de confiança do plug-in personalizado.

.Passos
. Navegue até a pasta que contém o armazenamento de chaves de plug-in personalizado _C: Arquivos de programas/NetApp/SnapCenter/SnapCenter Plug-in Creator/etc_
. Localize o arquivo _keystore.jks_.
. Liste os certificados adicionados no keystore:
+
_keytool -list -v -keystore keystore.jks_

. Adicione o certificado da CA com chave privada e pública.
+
_Keytool -importkeystore -srckeystore /root/SnapCenter.ssl.test.NetApp.com.pfx -srcstoretype PKCS12 -destinkeystore keystore.jks -deststoretype JKS_

. Liste os certificados adicionados no keystore.
+
_keytool -list -v -keystore keystore.jks_

. Verifique se o keystore contém o alias correspondente ao novo certificado da CA, que foi adicionado ao keystore.
. Altere a senha da chave privada adicionada para o certificado da CA para a senha do keystore.
+
A senha padrão do keystore do plug-in personalizado é o valor da chave KEYSTORE_PASS no arquivo agent.properties.

+
_Keytool -keypasswd -alias "alias_name_in_CA_cert" -keystore keystore.jks_

. Configure o nome do alias do certificado CA no arquivo _agent.properties_.
+
Atualize este valor com a chave SCC_CERTIFICATE_ALIAS.

. Reinicie o serviço depois de configurar o par de chaves assinadas pela CA para o armazenamento de confiança de plug-in personalizado.




== Configurar a lista de revogação de certificados (CRL) para plug-ins personalizados do SnapCenter

.Sobre esta tarefa
* Para transferir o ficheiro CRL mais recente para o certificado CA relacionado, https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_update_certificate_revocation_list_file_in_SnapCenter_CA_Certificate["Como atualizar o arquivo de lista de revogação de certificados no certificado da CA do SnapCenter"]consulte .
* Os plug-ins personalizados do SnapCenter pesquisarão os arquivos CRL em um diretório pré-configurado.
* O diretório padrão para os arquivos CRL para os plug-ins personalizados do SnapCenter é _'C: Arquivos de programas/NetApp/SnapCenter/SnapCenter Plug-in Creator etc/crl'_.


.Passos
. Você pode modificar e atualizar o diretório padrão no arquivo _agent.properties_ contra a chave CRL_PATH.
. Você pode colocar mais de um arquivo CRL neste diretório.
+
Os certificados recebidos serão verificados em relação a cada CRL.


