---
permalink: protect-nsp/configure_CA_certificate_on_Linux_host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Configure o certificado CA para o serviço de plug-ins compatíveis com NetApp no host Linux 
---
= Configure o certificado CA para o serviço de plug-ins compatíveis com NetApp no host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve gerenciar a senha do keystore do plug-in e seu certificado, configurar o certificado da CA, configurar certificados raiz ou intermediários para o trust-store do plug-in e configurar o par de chaves assinadas pela CA para o trust-store do plug-in com o serviço de plug-ins do SnapCenter para ativar o certificado digital instalado.

Os plug-ins usam o arquivo 'keystore.jks', que está localizado em _/opt/NetApp/snapcenter/scc/etc_ como seu armazenamento confiável e armazenamento de chaves.



== Gerenciar senha para keystore de plug-in e alias do par de chaves assinadas pela CA em uso

.Passos
. Você pode recuperar a senha padrão do keystore do plug-in a partir do arquivo de propriedades do agente do plug-in.
+
É o valor correspondente à chave 'KEYSTORE_PASS'.

. Altere a senha do keystore:
+
 keytool -storepasswd -keystore keystore.jks
. Altere a senha para todos os aliases de entradas de chave privada no keystore para a mesma senha usada para o keystore:
+
 keytool -keypasswd -alias "alias_name_in_cert" -keystore keystore.jks
+
Atualize o mesmo para a chave KEYSTORE_PASS no arquivo _agent.properties_.

. Reinicie o serviço depois de alterar a senha.



NOTE: A senha para o keystore do plug-in e para todas as senhas de alias associadas da chave privada deve ser a mesma.



== Configurar certificados raiz ou intermediários para plug-in trust-store

Você deve configurar os certificados raiz ou intermediários sem a chave privada para conectar o trust-store.

.Passos
. Navegue até a pasta que contém o keystore do plug-in: /opt/NetApp/snapcenter/scc/etc.
. Localize o arquivo 'keystore.jks'.
. Liste os certificados adicionados no keystore:
+
`keytool -list -v -keystore keystore.jks`

. Adicione um certificado raiz ou intermediário:
+
 keytool -import -trustcacerts -alias myRootCA -file /root/USERTrustRSA_Root.cer -keystore keystore.jks
. Reinicie o serviço após configurar os certificados raiz ou intermediários para conectar o trust-store.



NOTE: Você deve adicionar o certificado de CA raiz e, em seguida, os certificados de CA intermediários.



== Configurar o par de chaves assinadas pela CA para plug-in de armazenamento confiável

Você deve configurar o par de chaves assinadas pela CA para o trust-store do plug-in.

.Passos
. Navegue até a pasta que contém o keystore do plug-in /opt/NetApp/snapcenter/scc/etc.
. Localize o arquivo 'keystore.jks'.
. Liste os certificados adicionados no keystore:
+
`keytool -list -v -keystore keystore.jks`

. Adicione o certificado da CA com chave privada e pública.
+
`keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS`

. Liste os certificados adicionados no keystore.
+
`keytool -list -v -keystore keystore.jks`

. Verifique se o keystore contém o alias correspondente ao novo certificado da CA, que foi adicionado ao keystore.
. Altere a senha da chave privada adicionada para o certificado da CA para a senha do keystore.
+
A senha padrão do keystore do plug-in é o valor da chave KEYSTORE_PASS no arquivo agent.properties.

+
 keytool -keypasswd -alias "alias_name_in_CA_cert" -keystore keystore.jks
. Se o nome do alias no certificado da CA for longo e contiver espaço ou carateres especiais ("*",","), altere o nome do alias para um nome simples:
+
 keytool -changealias -alias "long_alias_name" -destalias "simple_alias" -keystore keystore.jks
. Configure o nome do alias do certificado CA no arquivo agent.properties.
+
Atualize este valor com a chave SCC_CERTIFICATE_ALIAS.

. Reinicie o serviço após configurar o par de chaves assinadas pela CA para o plug-in trust-store.




== Configurar a lista de revogação de certificados (CRL) para plug-ins

.Sobre esta tarefa
* Os plug-ins do SnapCenter procurarão os arquivos CRL em um diretório pré-configurado.
* O diretório padrão para os arquivos CRL dos plug-ins SnapCenter é ' opt/NetApp/snapcenter/scc/etc/crl'.


.Passos
. Você pode modificar e atualizar o diretório padrão no arquivo agent.properties contra a chave CRL_PATH.
+
Você pode colocar mais de um arquivo CRL neste diretório. Os certificados recebidos serão verificados em relação a cada CRL.


