---
permalink: protect-nsp/netapp_supported_plugins_features.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins features, MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, Storage plug-in 
summary: O SnapCenter se integra à aplicação plug-in e às tecnologias NetApp no sistema de storage. Para trabalhar com plug-ins compatíveis com NetApp, use a interface gráfica do usuário do SnapCenter. 
---
= NetApp recursos de plug-in suportados no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter se integra à aplicação plug-in e às tecnologias NetApp no sistema de storage. Para trabalhar com plug-ins compatíveis com NetApp, como MongoDB, ORASCPM (aplicações Oracle), SAP ASE, SAP MaxDB e plug-in de storage, você usa a interface gráfica de usuário do SnapCenter.

* * Interface gráfica unificada do usuário*
+
A interface do SnapCenter fornece padronização e consistência em plug-ins e ambientes. A interface do SnapCenter permite concluir operações consistentes de backup, restauração, recuperação e clone em plug-ins, usar relatórios centralizados, usar visualizações de dashboard rápidas, configurar controle de acesso baseado em funções (RBAC) e monitorar tarefas em todos os plug-ins.

* * Administração central automatizada*
+
Você pode agendar operações de backup, configurar a retenção de backup baseada em política e executar operações de restauração. Você também pode monitorar proativamente seu ambiente configurando o SnapCenter para enviar alertas por e-mail.

* *Tecnologia NetApp Snapshot sem interrupções*
+
O SnapCenter usa a tecnologia Snapshot do NetApp com os plug-ins compatíveis com o NetApp para fazer backup de recursos. Os snapshots consomem espaço mínimo de storage.



Os plug-ins compatíveis com NetApp também oferecem os seguintes benefícios:

* Suporte a fluxos de trabalho de backup, restauração e clone
* Delegação de funções centralizada e segurança compatível com RBAC
+
Você também pode definir as credenciais para que os usuários autorizados do SnapCenter tenham permissões no nível do aplicativo.

* Criação de cópias de recursos com uso eficiente de espaço e pontuais para teste ou extração de dados usando a tecnologia NetApp FlexClone
+
É necessária uma licença FlexClone no sistema de storage onde você deseja criar o clone.

* Suporte ao recurso Snapshot do grupo de consistência (CG) do ONTAP como parte da criação de backups.
* Funcionalidade de executar vários backups simultaneamente em vários hosts de recursos
+
Em uma única operação, os snapshots são consolidados quando os recursos em um único host compartilham o mesmo volume.

* Capacidade de criar Snapshot usando comandos externos.
* Capacidade de criar snapshots consistentes no sistema de arquivos em ambientes Windows.

