---
permalink: protect-nsp/netapp_supported_plugins_overview.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins, MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, Storage plug-in 
summary: Você pode desenvolver plug-ins compatíveis com NetApp para aplicações que usa e usar o SnapCenter para fazer backup, restauração ou clone dessas aplicações. Como outros plug-ins do SnapCenter, os plug-ins compatíveis com o NetApp funcionam como componentes do lado do host do software NetApp SnapCenter, permitindo a proteção de dados com reconhecimento de aplicações e o gerenciamento de recursos. 
---
= Visão geral dos plug-ins compatíveis com NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os plug-ins compatíveis com o NetApp, como MongoDB, ORASCPM (aplicações Oracle), SAP ASE, SAP MaxDB e plug-in de storage para aplicativos que você usa e depois usa o SnapCenter para fazer backup, restauração ou clonagem desses aplicativos. Seus plug-ins compatíveis com NetApp atuam como componentes do lado do host do software NetApp SnapCenter, permitindo a proteção de dados com reconhecimento de aplicações e o gerenciamento de recursos.

Quando os plug-ins compatíveis com NetApp estão instalados, você pode usar a tecnologia SnapCenter com NetApp SnapMirror para criar cópias espelhadas de conjuntos de backup em outro volume e usar a tecnologia NetApp SnapVault para executar a replicação de backup disco para disco. Os plug-ins compatíveis com NetApp podem ser usados em ambientes Windows e Linux.


NOTE: SnapCenterCLI não suporta comandos de plug-ins suportados pelo NetApp.

A NetApp fornece o plug-in de armazenamento para executar operações de proteção de dados do volume de dados no armazenamento ONTAP usando a estrutura de plug-in incorporada ao SnapCenter.

Você pode instalar os plug-ins compatíveis com o NetApp na página Adicionar host.

link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["Adicione hosts e instale pacotes plug-in em hosts remotos."^]


NOTE: A política de suporte do SnapCenter abrangerá o suporte à estrutura do plug-in, ao mecanismo principal e às APIs associadas. O suporte não abrangerá o código-fonte do plug-in e os scripts associados criados na estrutura do plug-in.
