---
permalink: protect-nsp/netapp_supported_plugins_overview.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins 
summary: Você pode desenvolver plug-ins compatíveis com NetApp para aplicações que usa e usar o SnapCenter para fazer backup, restauração ou clone dessas aplicações. Como outros plug-ins do SnapCenter, os plug-ins compatíveis com o NetApp funcionam como componentes do lado do host do software NetApp SnapCenter, permitindo a proteção de dados com reconhecimento de aplicações e o gerenciamento de recursos. 
---
= Visão geral dos plug-ins compatíveis com NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os plug-ins compatíveis com o NetApp ou desenvolver plug-ins personalizados para aplicativos que usam e, em seguida, usar o SnapCenter para fazer backup, restaurar ou clonar esses aplicativos. Seus plug-ins compatíveis com NetApp atuam como componentes do lado do host do software NetApp SnapCenter, permitindo a proteção de dados com reconhecimento de aplicações e o gerenciamento de recursos.

Quando os plug-ins compatíveis com NetApp estão instalados, você pode usar a tecnologia SnapCenter com NetApp SnapMirror para criar cópias espelhadas de conjuntos de backup em outro volume e usar a tecnologia NetApp SnapVault para executar a replicação de backup disco para disco. Os plug-ins compatíveis com NetApp podem ser usados em ambientes Windows e Linux.


NOTE: SnapCenterCLI não suporta comandos de plug-ins suportados pelo NetApp.

O NetApp fornece o plug-in de storage para executar operações de proteção de dados do volume de dados no storage ONTAP usando a estrutura de plug-in personalizada incorporada ao SnapCenter.

Você pode instalar os plug-ins compatíveis com o NetApp, plug-in personalizado e plug-in de armazenamento na página Adicionar host.

link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["Adicione hosts e instale pacotes plug-in em hosts remotos."^]

O NetApp também fornece plug-ins MongoDB, MySQL, PostgreSQL, Storage, MaxDB, Sybase ASE, ORASCPM, MongoDB e DPGlue.


NOTE: A política de suporte do SnapCenter cobrirá o suporte para a estrutura de plug-in personalizada do SnapCenter, mecanismo central e as APIs associadas. O suporte não cobrirá o código-fonte do plug-in e os scripts associados criados na estrutura de plug-in personalizada.

Você pode criar seus próprios plug-ins personalizados consultando link:develop_a_plug_in_for_your_application.html["Desenvolva um plug-in para sua aplicação"^]o guia.
