---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: Antes de adicionar um host e instalar os pacotes de plug-ins, você deve completar todos os requisitos. Os plug-ins compatíveis com NetApp podem ser usados em ambientes Windows, Linux ou AIX. 
---
= Pré-requisitos para adicionar hosts e instalar o pacote Plug-ins para Windows, Linux ou AIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de adicionar um host e instalar os pacotes de plug-ins, você deve completar todos os requisitos. Os plug-ins compatíveis com NetApp são compatíveis com ambientes Windows, Linux e AIX.


NOTE: Os aplicativos de armazenamento e Oracle são compatíveis com AIX.

* Você deve ter instalado o Java 11 em seu host Linux, Windows ou AIX.
+

NOTE: O IBM Java não é suportado em hosts Windows e Linux.

* Ao instalar um plug-in em um host do Windows, se você especificar uma credencial que não está integrada ou se o usuário pertence a um usuário local do grupo de trabalho, será necessário desativar o UAC no host.
* Os plug-ins compatíveis com o NetApp, como MongoDB, ORASCPM, aplicativos Oracle, SAP ASE, SAP MaxDB e plug-in de armazenamento, devem estar disponíveis no host do cliente de onde a operação de adição de host é executada.




== Geral

Se estiver a utilizar iSCSI, o serviço iSCSI deverá estar em execução.



== Hosts do Windows

* Você deve ter um usuário de domínio com Privileges de administrador local com permissões de login local no host remoto.
* Se você gerenciar nós de cluster no SnapCenter, precisará ter um usuário com Privileges administrativo para todos os nós do cluster.
* Você deve escolher manualmente o plug-in do SnapCenter para Microsoft Windows.
+
http://www.java.com/en/download/manual.jsp["Baixe JAVA para Windows"]





== Hosts Linux e AIX


NOTE: Os aplicativos de armazenamento e Oracle são compatíveis com AIX.

* Você deve ter habilitado a conexão SSH baseada em senha para o usuário root ou não root.
* Você deve ter instalado o Java 11 em seu host Linux.
+
Se você estiver usando o Windows Server 2019 ou o Windows Server 2016 para o host do servidor SnapCenter, você deve instalar o Java 11. A ferramenta de Matriz de interoperabilidade (IMT) contém as informações mais recentes sobre os requisitos.

+
http://www.java.com/en/download/manual.jsp["Baixe JAVA para Linux"]

+
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?license=IBM["Baixe JAVA para AIX"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"]

* Você deve configurar o sudo Privileges para que o usuário não-root forneça acesso a vários caminhos. Adicione as seguintes linhas ao arquivo /etc/sudoers usando o utilitário visudo Linux.
+

NOTE: Certifique-se de que está a utilizar o sudo versão 1.8.7 ou posterior.

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_LINUX_USER_ é o nome do usuário não-root que você criou.

+
Você pode obter o _checksum_value_ do arquivo *SC_unix_plugins_checksum.txt*, que está localizado em:

+
** Se o servidor SnapCenter estiver instalado no host do Windows, o SnapCenter NetApp não será instalado no sistema operacional Windows.
** _/opt/NetApp/SnapCenter/SnapManagerWeb/Repository/SC_UNIX_plugins_checksum.txt_ se o servidor SnapCenter estiver instalado no host Linux.
+

IMPORTANT: O exemplo deve ser usado apenas como referência para criar seus próprios dados.







== Requisitos de anfitrião do AIX

Você deve garantir que o host atenda aos requisitos antes de instalar o pacote de plug-ins do SnapCenter para AIX.


NOTE: Os aplicativos de armazenamento e Oracle são compatíveis com AIX.


NOTE: O plug-in do SnapCenter para UNIX, que faz parte do pacote de plug-ins do SnapCenter para AIX, não suporta grupos de volume simultâneos.

|===
| Item | Requisitos 


 a| 
Sistemas operacionais
 a| 
AIX 7,1 ou posterior



 a| 
RAM mínima para o plug-in SnapCenter no host
 a| 
4 GB



 a| 
Espaço mínimo de instalação e log para o plug-in SnapCenter no host
 a| 
2 GB


NOTE: Deve alocar espaço em disco suficiente e monitorizar o consumo de armazenamento pela pasta de registos. O espaço de registo necessário varia consoante o número de entidades a proteger e a frequência das operações de proteçãoão de dados. Se não houver espaço em disco suficiente, os logs não serão criados para as operações executadas recentemente.



 a| 
Pacotes de software necessários
 a| 
Java 11 IBM Java

Se você atualizou O JAVA para a versão mais recente, você deve garantir que a opção JAVA_HOME localizada em /var/opt/SnapCenter/spl/etc/spl.properties esteja definida para a versão JAVA correta e o caminho correto.

|===
Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].



=== Configure sudo Privileges para usuários não-root para host AIX

O SnapCenter 4,4 e posterior permite que um usuário não root instale o pacote de plug-ins do SnapCenter para AIX e inicie o processo de plug-in. Os processos de plug-in serão executados como um usuário não-root eficaz. Você deve configurar o sudo Privileges para que o usuário não-root forneça acesso a vários caminhos.

*O que você vai precisar*

* Sudo versão 1.8.7 ou posterior.
* Edite o arquivo _/etc/ssh/sshd_config_ para configurar os algoritmos de código de autenticação de mensagem: Macs hmac-SHA2-256 e MACs hmac-SHA2-512.
+
Reinicie o serviço sshd depois de atualizar o arquivo de configuração.

+
Exemplo:

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*Sobre esta tarefa*

Você deve configurar o sudo Privileges para que o usuário não-root forneça acesso aos seguintes caminhos:

* /Home/_AIX_USER_/.SC_NetApp/SnapCenter_aix_host_plugin.bsx
* /Custom_location/NetApp/SnapCenter/spl/installation/plugins/uninstall
* /Custom_location/NetApp/SnapCenter/spl/bin/spl


*Passos*

. Faça login no host AIX no qual você deseja instalar o pacote de plug-ins do SnapCenter para AIX.
. Adicione as seguintes linhas ao arquivo /etc/sudoers usando o utilitário visudo Linux.
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPACMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPACMD, PRECHECKCMD, CONFIGCHECKCMD, SCCMD
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+

NOTE: Se você estiver tendo uma configuração RAC, juntamente com os outros comandos permitidos, você deve adicionar o seguinte ao arquivo /etc/sudoers: '/<crs_home>/bin/olsnodes'



Você pode obter o valor de _crs_Home_ do arquivo _/etc/oracle/olr.loc_.

_AIX_USER_ é o nome do usuário não-root que você criou.

Você pode obter o _checksum_value_ do arquivo *SC_unix_plugins_checksum.txt*, que está localizado em:

* Se o servidor SnapCenter estiver instalado no host do Windows, o SnapCenter NetApp não será instalado no sistema operacional Windows.
* _/opt/NetApp/SnapCenter/SnapManagerWeb/Repository/SC_UNIX_plugins_checksum.txt_ se o servidor SnapCenter estiver instalado no host Linux.



IMPORTANT: O exemplo deve ser usado apenas como referência para criar seus próprios dados.
