---
permalink: protect-nsp/storage_types_supported_by_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins 
summary: O SnapCenter oferece suporte a uma ampla variedade de tipos de armazenamento em máquinas físicas e virtuais. Você deve verificar o suporte para seu tipo de storage antes de instalar os plug-ins compatíveis com NetApp. 
---
= Tipos de storage compatíveis com plug-ins compatíveis com NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter oferece suporte a uma ampla variedade de tipos de armazenamento em máquinas físicas e virtuais. Você deve verificar o suporte para seu tipo de storage antes de instalar os plug-ins compatíveis com NetApp.

|===
| Máquina | Tipo de armazenamento 


 a| 
Montagens físicas e diretas NFS nos hosts de VM (VMDKs e RDM LUNs não são compatíveis.)
 a| 
LUNs conectados a FC



 a| 
Montagens físicas e diretas NFS nos hosts de VM (VMDKs e RDM LUNs não são compatíveis.)
 a| 
LUNs ligados ao iSCSI



 a| 
Montagens físicas e diretas NFS nos hosts de VM (VMDKs e RDM LUNs não são compatíveis.)
 a| 
Volumes conectados a NFS



 a| 
VMware ESXi
 a| 
Armazenamentos de dados da VVol em NFS e SAN

O armazenamento de dados da VVol só pode ser provisionado com as Ferramentas do ONTAP para o VMware vSphere.

|===