---
permalink: protect-nsp/types_of_restore_strategies_supported_for_manually_added_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Você deve definir uma estratégia antes de executar operações de restauração com êxito usando o SnapCenter. Existem dois tipos de estratégias de restauração para recursos de plug-in compatíveis com NetApp adicionados manualmente. Não é possível recuperar recursos de plug-in suportados pelo NetApp adicionados manualmente. 
---
= NetApp estratégias de restauração de recursos de plug-in suportadas no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve definir uma estratégia antes de executar operações de restauração com êxito usando o SnapCenter. Existem dois tipos de estratégias de restauração para recursos de plug-in compatíveis com NetApp adicionados manualmente.


NOTE: Não é possível recuperar recursos de plug-in suportados pelo NetApp adicionados manualmente.



[[complete-resource-restore]]
== Restauração completa de recursos

* Restaura todos os volumes, qtrees e LUNs de um recurso



NOTE: Se o recurso contiver volumes ou qtrees, os instantâneos obtidos após o instantâneo selecionado para restauração nesses volumes ou qtrees serão excluídos e não poderão ser recuperados. Além disso, se qualquer outro recurso estiver hospedado nos mesmos volumes ou qtrees, esse recurso também será excluído.



[[file-level-restore]]
== Restauração no nível do arquivo

* Restaura arquivos de volumes, qtrees ou diretórios
* Restaura apenas os LUNs selecionados

