---
permalink: get-started/learn-about-snapcenter-support-for-asa-r2-systems.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: Você deve conhecer o sistema de storage suportado, as aplicações e os bancos de dados. 
---
= Operações SnapCenter suportadas para sistemas ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas de armazenamento ASA r2 são suportados a partir do SnapCenter 6.1. https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Saiba mais sobre os sistemas ASA R2"^] .

O SnapCenter oferece suporte à proteção primária e secundária de aplicativos executados em sistemas físicos e em sistemas de arquivos de máquina virtual (VMFS).  O SnapCenter usa APIs REST para todas as operações em sistemas ASA r2.  Os sistemas ASA r2 não suportam ZAPIs.

*Operações suportadas pelo SnapCenter para sistemas ASA r2*

* Criação de backups primários de aplicativos
* Movendo snapshots de grupos de consistência hierárquica para o sistema de armazenamento secundário
* Restaurar backups de sistemas de armazenamento primário e secundário para o host original ou alternativo
+
** Restauração no local de sistemas de armazenamento primário e secundário usando VMware vMotion
** Conecte e copie e restaure dos sistemas de armazenamento primário e secundário


* Clonar os backups para o host original ou para o host alternativo
* Mapeamento de dispositivo bruto (RDM)
* Proteção de volumes de aplicativos para Oracle
* Proteção do SAP HANA NDV
* LockVault
* Provisionamento secundário do diretório de log do host do plug-in SQL


O SnapCenter descobre ou cria grupos de consistência ONTAP .  Ele configura relacionamentos SnapMirror no cluster de destino para proteção secundária. https://docs.netapp.com/us-en/ontap/consistency-groups["Saiba mais sobre grupos de consistência ONTAP"^] .


NOTE: Após atualizar para o SnapCenter 6.2 (servidor e plug-ins) e o ONTAP 9.17.1, o SnapCenter altera grupos de consistência simples para grupos de consistência hierárquicos durante o primeiro backup agendado.

Para saber como habilitar a proteção secundária em sistemas ASA r2 para seu aplicativo, consulte:

* https://docs.netapp.com/us-en/snapcenter/protect-scsql/create-resource-groups-secondary-protection-for-asa-r2-mssql-resources.html["Habilitar proteção secundária para recursos do Microsoft SQL Server"]
* https://docs.netapp.com/us-en/snapcenter/protect-hana/create-resource-groups-secondary-protection-for-asa-r2-hana-resources.html["Habilitar proteção secundária para recursos do SAP HANA"]
* https://docs.netapp.com/us-en/snapcenter/protect-sco/create-resource-groups-secondary-protection-for-asa-r2-oracle-resources.html["Habilitar proteção secundária para recursos Oracle"]
* https://docs.netapp.com/us-en/snapcenter/protect-scw/create-resource-groups-secondary-protection-for-asa-r2-windows-file-systems.html["Habilitar proteção secundária para sistemas de arquivos do Windows"]
* https://docs.netapp.com/us-en/snapcenter/protect-db2/create-resource-groups-secondary-protection-for-asa-r2-db2-resources.html["Habilitar proteção secundária para recursos do IBM Db2"]
* https://docs.netapp.com/us-en/snapcenter/protect-postgresql/create-resource-groups-secondary-protection-for-asa-r2-postgresql-resources.html["Habilitar proteção secundária para recursos do PostgreSQL"]
* https://docs.netapp.com/us-en/snapcenter/protect-mysql/create-resource-groups-secondary-protection-for-asa-r2-mysql-resources.html["Habilitar proteção secundária para recursos do MySQL"]
* https://docs.netapp.com/us-en/snapcenter/protect-scu/create-resource-groups-secondary-protection-for-asa-r2-unix-resources.html["Habilitar proteção secundária para sistemas de arquivos Unix"]


*Operações não suportadas pelo SnapCenter para sistemas ASA r2*

* Snapshots à prova de violações
* Volumes FlexGroup
* Migração de sistemas de armazenamento ASA, AFF ou FAS para sistemas de armazenamento ASA r2
* Proteção de bancos de dados com uma combinação de recursos ASA, AFF ou FAS e recursos ASA r2
* Renomeação de snapshots
* Provisionamento de recursos do Windows
* Proteção secundária se houver failover de sincronização ativa do SnapMirror
* Protocolo de memória expressa não volátil (NVMe) se a sincronização ativa do SnapMirror estiver habilitada
* Proteção de aplicativos em execução no AIX
* Atualização técnica
* Recuperação de desastres de recursos do Microsoft SQL

