---
permalink: get-started/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: Você deve conhecer o sistema de storage suportado, as aplicações e os bancos de dados. 
---
= Sistemas e aplicações de storage com suporte da SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve conhecer os sistemas de storage, aplicações e bancos de dados compatíveis com o SnapCenter.



== Sistemas de storage compatíveis

* NetApp ONTAP 9.12.1 e posterior
* Azure NetApp Files
* Amazon FSX para NetApp ONTAP
+
O Amazon FSx for NetApp ONTAP oferece suporte à memória expressa não volátil (NVMe) por meio do Protocolo de Controle de Transporte (TCP).

+
Para obter informações sobre o Amazon FSX for NetApp ONTAP, https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Documentação do Amazon FSX para NetApp ONTAP"^] consulte .

* Sistemas NetApp ASA r2 que executam o NetApp ONTAP 9.16.1 e posterior
+
Você deve usar o ONTAP 9.17.1 se estiver usando o SnapCenter Server 6.2 e os plug-ins do SnapCenter 6.2.





== Aplicativos e bancos de dados compatíveis

O SnapCenter oferece suporte à proteção de diferentes aplicativos e bancos de dados.

O SnapCenter é compatível com a proteção de workloads Oracle e Microsoft SQL em ambientes de data center definido por software (SDDC) da Amazon. https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["Saiba mais"^].
