---
permalink: get-started/reference_data_security.html 
sidebar: sidebar 
keywords: security, authentication, CA certificates, FIPS, SSL, AES, TLS, RBAC, MFA, multi-factor authentication 
summary: A SnapCenter emprega recursos rígidos de segurança e autenticação para permitir que você mantenha seus dados seguros. 
---
= Recursos de segurança no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A SnapCenter emprega recursos rígidos de segurança e autenticação para permitir que você mantenha seus dados seguros.

O SnapCenter inclui os seguintes recursos de segurança:

* Toda a comunicação com o SnapCenter usa HTTP sobre SSL (HTTPS).
* Todas as credenciais no SnapCenter são protegidas usando criptografia AES (Advanced Encryption Standard).
* Suporta algoritmos de segurança compatíveis com o Federal Information Processing Standard (FIPS).
* Suporte ao uso dos certificados de CA autorizados fornecidos pelo cliente.
* Suporta TLS (Transport Layer Security) 1,3 para comunicação com o ONTAP. Você também pode usar o TLS 1,2 para comunicação entre clientes e servidores.
* Suporta um determinado conjunto de pacotes de criptografia SSL para fornecer segurança em toda a comunicação de rede. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_the_supported_SSL_Cipher_Suite["Saiba mais"].
* O SnapCenter é instalado no firewall da sua empresa para permitir o acesso ao servidor SnapCenter e para permitir a comunicação entre o servidor SnapCenter e os plug-ins.
* O acesso à API e à operação do SnapCenter usa tokens criptografados com criptografia AES, que expiram após 24 horas.
* O SnapCenter é integrado ao Windows active Directory para login e controle de acesso baseado em função (RBAC) que regem as permissões de acesso.
* O IPsec é compatível com o SnapCenter no ONTAP para máquinas host Windows e Linux. https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html#use-ipsec-identities["Saiba mais"].
* Os cmdlets do SnapCenter PowerShell são protegidos por sessão.
* Após um período padrão de 15 minutos de inatividade, o SnapCenter avisa que você será desconetado em 5 minutos.
+
Após 20 minutos de inatividade, o SnapCenter faz o logout e você deve fazer login novamente. Você pode modificar o período de logout.

* O início de sessão está temporariamente desativado após 5 tentativas de início de sessão incorretas.
* Suporta autenticação de certificado CA entre o servidor SnapCenter e o ONTAP. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_securely_connect_SnapCenter_with_ONTAP_using_CA_certificate["Saiba mais"].
* O verificador de integridade é adicionado ao servidor SnapCenter e aos plug-ins e valida todos os binários enviados durante novas operações de instalação e atualização.




== Visão geral do certificado CA

O instalador do servidor SnapCenter permite o suporte centralizado de certificados SSL durante a instalação. Para melhorar a comunicação segura entre o servidor e o plug-in, o SnapCenter suporta o uso dos certificados de CA autorizados fornecidos pelo cliente.

Você deve implantar certificados de CA depois de instalar o servidor SnapCenter e os respetivos plug-ins. Para obter mais informações, link:../install/reference_generate_CA_certificate_CSR_file.html["Gerar arquivo CSR do certificado CA"]consulte .

Você também pode implantar o certificado CA para o plug-in SnapCenter para VMware vSphere. Para obter mais informações, https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_and_import_certificates.html["Criar e importar certificados"^]consulte .



== Comunicação SSL bidirecional

A comunicação SSL bidirecional protege a comunicação mútua entre o servidor SnapCenter e os plug-ins.



== Visão geral da autenticação baseada em certificados

A autenticação baseada em certificado verifica a autenticidade dos respetivos usuários que tentam acessar o host do plug-in do SnapCenter. O usuário deve exportar o certificado do servidor SnapCenter sem chave privada e importá-lo no armazenamento confiável do host do plug-in. A autenticação baseada em certificado só funciona se o recurso SSL bidirecional estiver ativado.



== Autenticação multifator (MFA)

O MFA usa um provedor de identidade (IDP) de terceiros por meio da Security Assertion Markup Language (SAML) para gerenciar sessões de usuários. Esta funcionalidade melhora a segurança de autenticação, tendo a opção de utilizar vários fatores, como TOTP, biometria, notificações push, etc., juntamente com o nome de utilizador e palavra-passe existentes. Além disso, ele permite que o cliente use seus próprios provedores de identidade de usuário para obter login de usuário unificado (SSO) em todo o portfólio.

O MFA é aplicável apenas para login na IU do servidor SnapCenter. Os logins são autenticados por meio dos Serviços de Federação do ative Directory (AD FS) do IDP. Você pode configurar vários fatores de autenticação no AD FS. O SnapCenter é o provedor de serviços e você deve configurar o SnapCenter como uma parte confiável no AD FS. Para ativar o MFA no SnapCenter, você precisará dos metadados do AD FS.

Para obter informações sobre como ativar o MFA, link:../install/enable_multifactor_authentication.html["Ativar a autenticação multifator"]consulte .
