---
permalink: uninstall/task_remove_a_host.html 
sidebar: sidebar 
keywords: uninstall, remove, remove host 
summary: Quando o servidor SnapCenter remove um host, ele primeiro remove o backup, clones, tarefas de clone, grupos de recursos e recursos listados para esse host na página recursos do SnapCenter e, em seguida, desinstala os pacotes de plug-in no host. 
---
= Remova um host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando o servidor SnapCenter remove um host, ele primeiro remove o backup, clones, tarefas de clone, grupos de recursos e recursos listados para esse host na página recursos do SnapCenter e, em seguida, desinstala os pacotes de plug-in no host.

.Sobre esta tarefa
* Se você excluir um host, os backups, clones e grupos de recursos associados ao host também serão excluídos.
* Quando você remove os grupos de recursos, todas as programações associadas também são removidas.
* Se o host tiver um grupo de recursos compartilhado com outro host e você excluir o host, o grupo de recursos também será excluído.
* Você deve usar o cmdlet _Remove-SmHost_ para remover os hosts de plug-in desativados ou inacessíveis.
+
As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _get-Help command_name_. Em alternativa, pode também consultar https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência de cmdlet do software SnapCenter"^]

* O tempo necessário para remover um host depende do número de backups e das configurações de retenção. Isso ocorre porque os snapshots são excluídos de cada um dos controladores e os metadados são limpos.


.Passos
. No painel de navegação esquerdo, clique em *hosts*.
. Na página *hosts*, clique em *hosts gerenciados*.
. Selecione o host que deseja remover e clique em *Remover*.
. Para clusters do Oracle RAC, para remover o software SnapCenter de todos os hosts no cluster, selecione *incluir todos os hosts do cluster*.
+
Você também pode remover um nó de um cluster e, dessa forma, remover todos os nós um por um.

. Clique em *OK*.
+

NOTE: Quando você desinstalar e reinstalar os plug-ins do host em um cluster, os recursos do cluster não são detetados automaticamente. Selecione o nome do host do cluster e clique em *Atualizar recursos* para descobrir automaticamente os recursos do cluster.


