---
permalink: release-notes/release-notes.html 
sidebar: sidebar 
keywords: release notes, snapcenter 
summary: Fornece informações importantes sobre esta versão do servidor SnapCenter e os pacotes plug-in do SnapCenter, incluindo problemas corrigidos, problemas conhecidos, precauções e limitações. 
---
= Notas de lançamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conheça os novos recursos e melhorias disponíveis nas versões 6.2, 6.2.1 e 6.2.2 do SnapCenter.

Para obter uma lista completa dos novos recursos e melhorias, consulte link:what's-new-in-snapcenter622.html["O que há de novo no SnapCenter 6.2.2"].

Para obter uma lista completa dos novos recursos e melhorias, consulte link:what's-new-in-snapcenter621.html["O que há de novo no SnapCenter 6.2.1"].

Para obter uma lista completa dos novos recursos e melhorias, consulte link:what's-new-in-snapcenter62.html["Novidades no SnapCenter 6.2"].

Para obter detalhes sobre problemas conhecidos, limitações, problemas corrigidos e comandos novos e alterados, consulte as  https://library.netapp.com/ecm/ecm_download_file/ECMLP3359467["SnapCenter Software 6.2.2 Notas de lançamento"^]. Você precisa fazer login com sua NetApp conta ou criar uma conta para acessar as Notas de Versão.
