---
permalink: 'release-notes/what"s-new-in-snapcenter601.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0.1 
summary: A versão 6.0.1 do software SnapCenter inclui vários novos recursos e aprimoramentos. 
---
= Novidades do software SnapCenter 6.0.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A versão 6.0.1 do software SnapCenter inclui vários novos recursos e aprimoramentos.

|===
| Atualização | Descrição 


| link:https://docs.netapp.com/us-en/snapcenter/protect-azure/protect-applications-azure-netapp-files.html["Suporte para backup Azure NetApp Files"]  a| 
O SnapCenter dá suporte ao recurso de backup do Azure NetApp Files que expande os recursos de proteção de dados do Azure NetApp Files fornecendo solução de backup totalmente gerenciada para recuperação, arquivamento e conformidade de longo prazo.



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Suporte para alta disponibilidade de SnapCenter em execução no Linux"]  a| 
Configure a alta disponibilidade no SnapCenter em execução no Windows ou Linux usando o balanceador de carga F5, o balanceamento de carga de rede (NLB), o balanceamento de carga elástico (ELB) da Amazon Web Services (AWS) ou o balanceador de carga do Azure.



| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-scheduled-backup-jobs["Suporte para gerenciar trabalhos de backup programados"]  a| 
Permite-lhe definir um limite para o número de trabalhos agendados que podem ser executados a qualquer momento. Isso permite que você controle o número de backups que deseja executar com base na configuração de hardware do seu sistema.



| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-stale-jobs["Suporte para gerenciar trabalhos obsoletos"]  a| 
Permite-lhe limpar trabalhos obsoletos que estão presos durante mais de 72 horas.



| Suporte para IBM DB2, Oracle Application e Storage plug-in no AIX  a| 
Oferece suporte à proteção de dados do plug-in IBM DB2, Oracle Application e Storage no AIX

|===