---
permalink: 'release-notes/what"s-new-in-snapcenter601.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0.1 
summary: A versão 6.0.1 do software SnapCenter inclui vários novos recursos e aprimoramentos. 
---
= Novidades do software SnapCenter 6.0.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A versão 6.0.1 do software SnapCenter inclui vários novos recursos e aprimoramentos.

|===
| Atualização | Descrição 


| link:https://docs.netapp.com/us-en/snapcenter/protect-azure/protect-applications-azure-netapp-files.html["Suporte para backup Azure NetApp Files"]  a| 
Agora você pode usar o SnapCenter para fazer backup e clonar aplicativos que residem no Azure NetApp Files para armazenamento de Blobs do Azure (armazenamento de objetos).



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Suporte para alta disponibilidade de SnapCenter em execução no Linux"]  a| 
O suporte para configuração de HA para SnapCenter agora é estendido para sistemas Linux. Você pode usar os balanceadores de carga padrão para esta configuração:

* F5 balanceador de carga
* Balanceamento de carga de rede da Microsoft (NLB)
* Amazon Web Services (AWS)
* Balanceamento de carga elástico (ELB)
* Balanceador de carga do Azure




| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-scheduled-backup-jobs["Capacidade de gerir trabalhos de cópia de segurança programados"]  a| 
Agora você pode definir um limite para os trabalhos agendados para controlar o número de backups que deseja executar em um determinado momento com base na configuração de hardware do sistema.



| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-stale-jobs["Capacidade de gerenciar trabalhos obsoletos"]  a| 
Agora você pode definir um agendamento predefinido para limpar trabalhos obsoletos que estão presos por mais de 72 horas.



| Funcionalidade de proteção de dados incluída para IBM DB2, Oracle Application e Storage plug-in em execução no AIX  a| 
Oferece suporte à proteção de dados do plug-in IBM DB2, Oracle Application e Storage em execução no AIX.

|===