---
permalink: 'release-notes/what"s-new-in-snapcenter61.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.2 
summary: A versão 6,1 do software SnapCenter inclui vários novos recursos e aprimoramentos. 
---
= Novidades no SnapCenter software 6.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A versão 6.2 do SnapCenter software inclui o seguinte novo recurso.

|===
| Atualização | Descrição 


| link:../get-started/reference_supported_storage_systems_and_applications.html["Suporte para sistemas ASA R2"]  a| 
O SnapCenter 6.2 (servidor e plug-ins), juntamente com o ONTAP 9.17.1, oferece suporte à proteção primária e secundária de aplicativos executados em sistemas físicos (Linux e Windows) e em sistemas de arquivos de máquinas virtuais (VMFS), utilizando grupos de consistência hierárquicos.

Após a atualização para o SnapCenter 6.2 e o ONTAP 9.17.1, o SnapCenter altera grupos de consistência simples para grupos de consistência hierárquicos durante o primeiro backup agendado.

|===


== BlueXP agora é NetApp Console

O NetApp Console, criado com base na base aprimorada e reestruturada do BlueXP , fornece gerenciamento centralizado do armazenamento NetApp e do NetApp Data Services em ambientes locais e na nuvem em nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada, de forma altamente segura e compatível.

Para obter detalhes sobre o que mudou, consulte olink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de versão do NetApp Console"^] .
