---
permalink: protect-mysql/define-a-backup-strategy-for-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: 'Definir uma estratégia de backup antes de criar seus trabalhos de backup ajuda a ter os backups necessários para restaurar ou clonar seus recursos com êxito. Seu contrato de nível de serviço (SLA), objetivo de tempo de recuperação (rto) e objetivo de ponto de recuperação (RPO) determinam em grande parte sua estratégia de backup.' 
---
= Defina uma estratégia de backup para MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definir uma estratégia de backup antes de criar seus trabalhos de backup ajuda a ter os backups necessários para restaurar ou clonar seus recursos com êxito. Seu contrato de nível de serviço (SLA), objetivo de tempo de recuperação (rto) e objetivo do ponto de restauração (RPO) determinam em grande parte a sua estratégia de backup.

.Sobre esta tarefa
Um SLA define o nível de serviço esperado e aborda muitos problemas relacionados ao serviço, incluindo a disponibilidade e o desempenho do serviço. Rto é o momento em que um processo de negócios deve ser restaurado após uma interrupção no serviço. O RPO define a estratégia para a era dos arquivos que precisam ser recuperados do armazenamento de backup para que as operações regulares sejam retomadas após uma falha. SLA, rto e RPO contribuem para a estratégia de proteção de dados.

.Passos
. Determine quando você deve fazer backup de seus recursos.
. Decida quantos trabalhos de cópia de segurança necessita.
. Decida como nomear seus backups.
. Decida se você deseja criar uma política baseada em cópia Snapshot para fazer backup de snapshots consistentes com aplicativos do banco de dados.
. Decida se você deseja usar a tecnologia NetApp SnapMirror para replicação ou a tecnologia NetApp SnapVault para retenção a longo prazo.
. Determine o período de retenção dos snapshots no sistema de storage de origem e no destino do SnapMirror.
. Determine se deseja executar quaisquer comandos antes ou depois da operação de backup e forneça um prescritor ou postscript.

