---
permalink: protect-mysql/how-resources-resource-groups-and-policies-are-used-for-protecting-mysql.html 
sidebar: sidebar 
keywords: MySQL 
summary: Antes de usar o SnapCenter, é útil entender conceitos básicos relacionados às operações de backup, clonagem e restauração que você deseja executar. Você interage com recursos, grupos de recursos e políticas para diferentes operações. 
---
= Como recursos, grupos de recursos e políticas são usados para proteger o MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o SnapCenter, é útil entender conceitos básicos relacionados às operações de backup, clonagem e restauração que você deseja executar. Você interage com recursos, grupos de recursos e políticas para diferentes operações.

* Os recursos geralmente são instâncias do MySQL que você faz backup ou clonar com o SnapCenter.
* Um grupo de recursos do SnapCenter é uma coleção de recursos em um host.
+
Quando você executa uma operação em um grupo de recursos, executa essa operação nos recursos definidos no grupo de recursos de acordo com a programação especificada para o grupo de recursos.

+
Você pode fazer backup sob demanda de um único recurso ou de um grupo de recursos. Você também pode executar backups programados para recursos únicos e grupos de recursos.

* As políticas especificam a frequência do backup, a replicação, os scripts e outras caraterísticas das operações de proteção de dados.
+
Ao criar um grupo de recursos, você seleciona uma ou mais políticas para esse grupo. Você também pode selecionar uma política quando você executa um backup sob demanda para um único recurso.



Pense em um grupo de recursos como definindo o que você quer proteger e quando você quer protegê-lo em termos de dia e tempo. Pense em uma política como definir como você deseja protegê-la. Se você estiver fazendo backup de todos os bancos de dados, por exemplo, poderá criar um grupo de recursos que inclua todos os bancos de dados no host. Em seguida, você pode anexar duas políticas ao grupo de recursos: Uma política diária e uma política por hora. Ao criar o grupo de recursos e anexar as políticas, você pode configurar o grupo de recursos para executar um backup completo diariamente.
