---
permalink: protect-mysql/types-of-restore-performed-for-auto-discovered-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for mysql 
summary: 'O SnapCenter suporta o SnapRestore baseado em volume (VBSR), o SnapRestore de arquivo único e os tipos de restauração conectar e copiar para bancos de dados MySQL descobertos automaticamente.' 
---
= Tipos de restauração para bancos de dados MySQL descobertos automaticamente no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O plug-in do SnapCenter para MySQL suporta SnapRestore de arquivo único e tipos de restauração de conexão e cópia para bancos de dados MySQL descobertos automaticamente.



[[single-file-snaprestore-is-performed-in-nfs-environments-for-the-following-scenarios]]
== O SnapRestore de arquivo único é executado em ambientes NFS para os seguintes cenários:

* Se apenas a opção *Complete Resource* estiver selecionada
* Quando o backup selecionado é de um local secundário SnapMirror ou SnapVault e a opção *recurso completo* está selecionada




[[single-file-snaprestore-is-performed-in-san-environments-for-the-following-scenarios]]
== O SnapRestore de Arquivo único é executado em ambientes SAN para os seguintes cenários:

* Se apenas a opção *Complete Resource* estiver selecionada
* Quando o backup é selecionado em um local secundário do SnapMirror ou do SnapVault e a opção *recurso completo* está selecionada

